import type { Metadata } from "next";
import Container from "@/app/components/shared/Container";
import SchemaMarkup from "@/app/components/shared/SchemaMarkup";
import { BRAND } from "@/lib/constants";

export const metadata: Metadata = {
  title: "Terms of Service — AlecRae",
  description:
    "Terms of Service governing your use of the AlecRae professional intelligence platform, including AlecRae Legal, AlecRae Accounting, The Oracle, AlecRae Voice, and AlecRae Courtroom.",
};

const EFFECTIVE_DATE = "3 April 2026";

const schema = {
  "@context": "https://schema.org",
  "@type": "WebPage",
  name: "Terms of Service — AlecRae",
  description: "Terms of Service governing use of the AlecRae platform.",
  url: "https://alecrae.com/terms",
};

export default function TermsPage() {
  return (
    <>
      <SchemaMarkup schema={schema} />
      <section className="bg-navy-500 pt-32 pb-20 sm:pt-40 sm:pb-28">
        <Container className="text-center">
          <p className="text-sm font-semibold tracking-wider text-forest-300">
            Legal
          </p>
          <h1 className="mt-6 font-serif text-hero text-white">
            Terms of Service
          </h1>
          <p className="mx-auto mt-6 max-w-xl text-lg text-navy-200">
            Effective date: {EFFECTIVE_DATE}
          </p>
        </Container>
      </section>

      <section className="py-24 sm:py-36">
        <Container narrow>
          <div className="prose prose-navy max-w-none text-navy-600 [&_h2]:font-serif [&_h2]:text-navy-800 [&_h3]:text-navy-700 [&_h2]:text-2xl [&_h3]:text-lg [&_strong]:text-navy-700 [&_a]:text-forest-600 [&_a]:underline">

            <p className="text-sm text-navy-400">
              Last updated: {EFFECTIVE_DATE}
            </p>

            <h2>1. Agreement to Terms</h2>
            <p>
              These Terms of Service (&ldquo;Terms&rdquo;, &ldquo;Agreement&rdquo;) constitute a legally binding
              contract between you (&ldquo;User&rdquo;, &ldquo;you&rdquo;, &ldquo;your&rdquo;) and AlecRae Ltd
              (New Zealand), and its affiliated entities including
              AlecRae IP Holdings Ltd (New Zealand), AlecRae Inc (Delaware, USA),
              AlecRae Pty Ltd (Australia), and AlecRae Ltd (UK)
              (collectively, &ldquo;AlecRae&rdquo;, &ldquo;we&rdquo;, &ldquo;us&rdquo;, &ldquo;our&rdquo;),
              governing your access to and use of the AlecRae platform, including all associated
              websites, applications, APIs, products, and services (collectively, the &ldquo;Platform&rdquo;
              or &ldquo;Services&rdquo;).
            </p>
            <p>
              <strong>By accessing or using the Platform, you acknowledge that you have read,
              understood, and agree to be bound by these Terms, our Privacy Policy, our
              Acceptable Use Policy, and our Disclaimer, all of which are incorporated herein
              by reference.</strong> If you do not agree to these Terms, you must not access or
              use the Platform.
            </p>
            <p>
              If you are using the Platform on behalf of an organisation, you represent and
              warrant that you have the authority to bind that organisation to these Terms.
              In such cases, &ldquo;you&rdquo; and &ldquo;your&rdquo; refer to that organisation.
            </p>

            <h2>2. Definitions</h2>
            <p>In these Terms, the following definitions apply:</p>
            <ul>
              <li><strong>&ldquo;Content&rdquo;</strong> means any data, text, documents, files, images, audio, video, or other materials uploaded, submitted, stored, or transmitted through the Platform.</li>
              <li><strong>&ldquo;AI Output&rdquo;</strong> means any text, analysis, research results, citations, recommendations, document drafts, or other content generated by the Platform&rsquo;s artificial intelligence systems, including but not limited to The Oracle, Document AI, and AlecRae Voice.</li>
              <li><strong>&ldquo;Professional User&rdquo;</strong> means a licensed attorney, certified public accountant, chartered accountant, or other qualified professional using the Platform in a professional capacity.</li>
              <li><strong>&ldquo;Client Data&rdquo;</strong> means any data pertaining to the Professional User&rsquo;s clients, including but not limited to personal information, financial records, legal documents, communications, and case materials.</li>
              <li><strong>&ldquo;Trust Funds&rdquo;</strong> means any funds held in IOLTA or equivalent trust accounts managed through the Platform.</li>
              <li><strong>&ldquo;Subscription&rdquo;</strong> means the paid plan that governs your access tier and feature availability on the Platform.</li>
            </ul>

            <h2>3. Eligibility</h2>
            <p>
              You must be at least 18 years of age and possess the legal capacity to enter
              into a binding contract in your jurisdiction to use the Platform. Certain features
              of the Platform, including trust accounting and court filing, are restricted to
              licensed professionals who hold valid, current professional credentials in their
              respective jurisdictions.
            </p>
            <p>
              We reserve the right to verify your professional credentials at any time and to
              suspend or terminate your access if your credentials are found to be invalid,
              expired, suspended, or revoked.
            </p>

            <h2>4. The Platform Is a Tool &mdash; Not a Professional Service Provider</h2>
            <p>
              <strong>THE PLATFORM IS A TECHNOLOGY TOOL DESIGNED TO ASSIST LICENSED PROFESSIONALS
              IN THE PERFORMANCE OF THEIR PROFESSIONAL DUTIES. THE PLATFORM DOES NOT ITSELF
              PRACTISE LAW, PROVIDE LEGAL ADVICE, PROVIDE ACCOUNTING SERVICES, PROVIDE TAX
              ADVICE, OR PROVIDE ANY OTHER PROFESSIONAL SERVICE.</strong>
            </p>
            <p>
              No AI Output, research result, citation, document draft, tax calculation,
              compliance recommendation, or any other content generated by the Platform
              constitutes legal advice, tax advice, accounting advice, or professional advice
              of any kind. The Platform does not create, and shall not be construed as creating,
              an attorney-client relationship, accountant-client relationship, fiduciary
              relationship, or any other professional-client relationship between AlecRae and
              any user or any user&rsquo;s client.
            </p>
            <p>
              <strong>Professional Users bear sole and exclusive responsibility for:</strong>
            </p>
            <ul>
              <li>Reviewing, verifying, and validating all AI Output before use or reliance;</li>
              <li>Exercising independent professional judgment on all matters;</li>
              <li>Ensuring compliance with all applicable professional conduct rules, ethical obligations, and regulatory requirements in their jurisdiction;</li>
              <li>Maintaining all required professional licences, certifications, and insurance;</li>
              <li>Determining the suitability, accuracy, and completeness of any AI Output for their specific use case;</li>
              <li>All decisions made and actions taken based on AI Output, whether or not the AI Output was accurate.</li>
            </ul>

            <h2>5. AI Output &mdash; No Warranty of Accuracy</h2>
            <p>
              AI Output is generated by machine learning systems and large language models.
              While AlecRae employs citation verification, hallucination prevention, and
              quality assurance measures, <strong>AI Output may contain errors, omissions,
              inaccuracies, outdated information, or fabricated content (&ldquo;hallucinations&rdquo;).</strong>
            </p>
            <p>
              The Oracle&rsquo;s citation verification system assigns verification badges
              (Verified, Unverified, Not Found) to citations based on automated cross-referencing
              with authoritative public domain sources. These badges represent the outcome of an
              automated verification process only and do not constitute a guarantee of accuracy,
              completeness, currency, or applicability to any specific legal or accounting matter.
            </p>
            <p>
              <strong>You acknowledge and agree that:</strong>
            </p>
            <ul>
              <li>AI Output is provided &ldquo;as is&rdquo; and &ldquo;as available&rdquo; without any warranty of accuracy, completeness, reliability, timeliness, or fitness for any particular purpose;</li>
              <li>You will independently verify all AI Output, including all citations, case references, statutory references, tax calculations, regulatory interpretations, and compliance recommendations, before reliance;</li>
              <li>An &ldquo;Unverified&rdquo; or &ldquo;Not Found&rdquo; badge is an explicit warning that the citation has not been confirmed and must be independently verified;</li>
              <li>Even a &ldquo;Verified&rdquo; badge does not guarantee that the citation is current, correctly applied, or relevant to your specific matter;</li>
              <li>AlecRae shall have no liability whatsoever for any loss, damage, sanction, penalty, malpractice claim, professional discipline, or other adverse consequence arising from reliance on AI Output.</li>
            </ul>

            <h2>6. Account Registration and Security</h2>
            <p>
              You must provide accurate, current, and complete information during registration
              and maintain the accuracy of such information. You are solely responsible for
              safeguarding your account credentials and for all activity that occurs under your
              account. You must immediately notify AlecRae of any unauthorised use of your
              account or any other breach of security.
            </p>
            <p>
              AlecRae reserves the right to suspend or terminate accounts that are inactive
              for extended periods, exhibit suspicious activity, or violate these Terms.
            </p>

            <h2>7. Subscriptions, Fees, and Payment</h2>
            <h3>7.1 Subscription Plans</h3>
            <p>
              Access to the Platform is governed by subscription plans as published on
              our <a href="/pricing">Pricing</a> page. Feature availability varies by plan tier.
              AlecRae reserves the right to modify subscription plans, features, and pricing
              at any time upon 30 days&rsquo; written notice.
            </p>
            <h3>7.2 Payment Terms</h3>
            <p>
              All fees are quoted in United States Dollars (USD) unless otherwise specified.
              Subscriptions are billed in advance on a monthly or annual basis as selected
              at the time of purchase. All payments are processed through our third-party
              payment processor (currently Stripe, Inc.) and are subject to their terms of
              service.
            </p>
            <h3>7.3 Taxes</h3>
            <p>
              All fees are exclusive of applicable taxes. You are responsible for all taxes,
              duties, levies, and charges imposed by any governmental authority in connection
              with your use of the Platform, including but not limited to GST (New Zealand and
              Australia), VAT (United Kingdom and European Union), and sales tax (United States).
              AlecRae will collect and remit applicable taxes where required by law.
            </p>
            <h3>7.4 Refunds</h3>
            <p>
              Except as required by applicable consumer protection law (including the
              New Zealand Consumer Guarantees Act 1993, Australian Consumer Law, UK Consumer
              Rights Act 2015, and equivalent US state consumer protection statutes), all
              fees are non-refundable. If you believe you are entitled to a refund under
              applicable law, contact us at legal@alecrae.com.
            </p>
            <h3>7.5 Failure to Pay</h3>
            <p>
              If payment fails, AlecRae may suspend access to the Platform after providing
              7 days&rsquo; notice. Continued failure to pay may result in termination of your
              account. AlecRae reserves the right to recover outstanding fees through
              collection proceedings and to charge interest on overdue amounts at the maximum
              rate permitted by applicable law.
            </p>

            <h2>8. Intellectual Property</h2>
            <h3>8.1 AlecRae IP</h3>
            <p>
              The Platform, including all software, algorithms, machine learning models,
              user interfaces, designs, trademarks, trade names, logos, documentation, and
              all other intellectual property embodied in or associated with the Platform
              (collectively, &ldquo;AlecRae IP&rdquo;), is owned exclusively by AlecRae IP Holdings Ltd
              (New Zealand) and is licensed to the operating entities for distribution. AlecRae
              IP is protected by copyright, trademark, patent, trade secret, and other
              intellectual property laws of New Zealand, the United States, Australia, the
              United Kingdom, and international treaties.
            </p>
            <p>
              Nothing in these Terms grants you any right, title, or interest in AlecRae IP
              except for the limited right to access and use the Platform in accordance with
              these Terms during your active Subscription.
            </p>
            <h3>8.2 Your Content</h3>
            <p>
              You retain all rights in your Content. By uploading Content to the Platform,
              you grant AlecRae a limited, non-exclusive, worldwide, royalty-free licence to
              store, process, transmit, and display your Content solely for the purpose of
              providing the Services to you. This licence terminates when you delete your
              Content or close your account, subject to reasonable backup retention periods
              and legal hold obligations.
            </p>
            <p>
              <strong>AlecRae does not use your Content, Client Data, or any user-uploaded
              materials to train, fine-tune, or improve its AI models.</strong> Your data is
              your data. Period.
            </p>
            <h3>8.3 Feedback</h3>
            <p>
              If you provide feedback, suggestions, or ideas regarding the Platform
              (&ldquo;Feedback&rdquo;), you grant AlecRae an irrevocable, perpetual, worldwide,
              royalty-free licence to use, modify, and incorporate such Feedback into the
              Platform without obligation to you.
            </p>

            <h2>9. Data Protection and Privacy</h2>
            <p>
              Your use of the Platform is subject to our <a href="/privacy">Privacy Policy</a>,
              which describes how we collect, use, store, and protect your personal information.
              The Privacy Policy is incorporated into these Terms by reference.
            </p>
            <p>
              Where the Platform processes personal data on behalf of Professional Users
              (i.e., Client Data), AlecRae acts as a data processor (or sub-processor) under
              applicable data protection law. A Data Processing Agreement (&ldquo;DPA&rdquo;) is
              available upon request for enterprise customers and is required where GDPR, UK
              GDPR, the NZ Privacy Act 2020, or the Australian Privacy Act 1988 applies to
              the processing.
            </p>

            <h2>10. Trust Accounting</h2>
            <p>
              The Platform&rsquo;s trust accounting features are designed to assist Professional
              Users in managing IOLTA and equivalent trust accounts in compliance with their
              jurisdictional requirements. <strong>AlecRae does not hold, control, or have access
              to Trust Funds.</strong> All Trust Funds are held at third-party financial institutions
              selected and controlled by the Professional User.
            </p>
            <p>
              The Professional User is solely responsible for compliance with all applicable
              trust accounting rules, including but not limited to the rules of the relevant
              state bar, law society, or accounting body. AlecRae provides technology tools
              to facilitate record-keeping and reconciliation but does not guarantee compliance
              with any specific jurisdictional requirement.
            </p>

            <h2>11. Acceptable Use</h2>
            <p>
              Your use of the Platform is subject to our <a href="/acceptable-use">Acceptable
              Use Policy</a>, which is incorporated into these Terms by reference. You agree
              not to use the Platform for any purpose that is unlawful, harmful, fraudulent,
              deceptive, or that violates these Terms or any applicable law.
            </p>

            <h2>12. Limitation of Liability</h2>
            <p>
              <strong>TO THE MAXIMUM EXTENT PERMITTED BY APPLICABLE LAW:</strong>
            </p>
            <h3>12.1 Exclusion of Consequential Damages</h3>
            <p>
              IN NO EVENT SHALL ALECRAE, ITS AFFILIATES, DIRECTORS, OFFICERS, EMPLOYEES,
              AGENTS, CONTRACTORS, LICENSORS, OR SUPPLIERS BE LIABLE FOR ANY INDIRECT,
              INCIDENTAL, SPECIAL, CONSEQUENTIAL, PUNITIVE, OR EXEMPLARY DAMAGES, INCLUDING
              BUT NOT LIMITED TO DAMAGES FOR LOSS OF PROFITS, REVENUE, GOODWILL, DATA, USE,
              OR OTHER INTANGIBLE LOSSES, ARISING OUT OF OR IN CONNECTION WITH YOUR USE OF
              OR INABILITY TO USE THE PLATFORM, EVEN IF ALECRAE HAS BEEN ADVISED OF THE
              POSSIBILITY OF SUCH DAMAGES.
            </p>
            <h3>12.2 Cap on Liability</h3>
            <p>
              ALECRAE&rsquo;S TOTAL AGGREGATE LIABILITY TO YOU FOR ALL CLAIMS ARISING OUT OF
              OR IN CONNECTION WITH THESE TERMS OR YOUR USE OF THE PLATFORM SHALL NOT EXCEED
              THE GREATER OF (A) THE TOTAL FEES PAID BY YOU TO ALECRAE DURING THE TWELVE (12)
              MONTHS IMMEDIATELY PRECEDING THE EVENT GIVING RISE TO THE CLAIM, OR (B) ONE
              HUNDRED UNITED STATES DOLLARS (USD $100.00).
            </p>
            <h3>12.3 Specific Exclusions</h3>
            <p>
              Without limiting the generality of the foregoing, AlecRae shall have no liability
              whatsoever for:
            </p>
            <ul>
              <li>Any loss, damage, sanction, penalty, malpractice claim, bar complaint, disciplinary action, or other adverse consequence arising from a Professional User&rsquo;s reliance on AI Output without independent verification;</li>
              <li>Any citation, case reference, statutory reference, or regulatory interpretation contained in AI Output that is inaccurate, fabricated, outdated, overruled, superseded, or inapplicable;</li>
              <li>Any loss arising from unauthorised access to your account caused by your failure to maintain adequate security;</li>
              <li>Any loss arising from the acts or omissions of third-party service providers, including payment processors, cloud infrastructure providers, and banking connectivity providers;</li>
              <li>Any loss of Client Data caused by circumstances beyond AlecRae&rsquo;s reasonable control;</li>
              <li>Any loss arising from modifications to the Platform, including changes to features, functionality, or pricing;</li>
              <li>Any tax liability, penalty, or interest arising from reliance on tax calculations, compliance recommendations, or regulatory interpretations generated by the Platform.</li>
            </ul>
            <h3>12.4 Consumer Protection Savings</h3>
            <p>
              Nothing in these Terms excludes or limits liability that cannot be excluded or
              limited under applicable law, including but not limited to: the New Zealand
              Consumer Guarantees Act 1993; the Australian Consumer Law (Schedule 2 to the
              Competition and Consumer Act 2010); the UK Consumer Rights Act 2015; and
              applicable US state consumer protection statutes. Where such laws apply and
              cannot be contractually excluded, AlecRae&rsquo;s liability is limited to the
              maximum extent permitted.
            </p>

            <h2>13. Indemnification</h2>
            <p>
              You agree to indemnify, defend, and hold harmless AlecRae and its affiliates,
              directors, officers, employees, agents, contractors, and licensors from and
              against any and all claims, demands, losses, damages, liabilities, costs, and
              expenses (including reasonable attorneys&rsquo; fees and court costs) arising out
              of or in connection with:
            </p>
            <ul>
              <li>Your use of or inability to use the Platform;</li>
              <li>Your violation of these Terms or any applicable law;</li>
              <li>Your Content or Client Data;</li>
              <li>Your reliance on AI Output;</li>
              <li>Any claim by a third party (including your clients) arising from your professional services or your use of the Platform in connection with those services;</li>
              <li>Your violation of any third-party rights, including intellectual property rights and privacy rights.</li>
            </ul>

            <h2>14. Disclaimer of Warranties</h2>
            <p>
              <strong>THE PLATFORM IS PROVIDED &ldquo;AS IS&rdquo; AND &ldquo;AS AVAILABLE&rdquo; WITHOUT
              WARRANTIES OF ANY KIND, WHETHER EXPRESS, IMPLIED, STATUTORY, OR OTHERWISE.
              TO THE MAXIMUM EXTENT PERMITTED BY APPLICABLE LAW, ALECRAE DISCLAIMS ALL
              WARRANTIES, INCLUDING BUT NOT LIMITED TO IMPLIED WARRANTIES OF MERCHANTABILITY,
              FITNESS FOR A PARTICULAR PURPOSE, NON-INFRINGEMENT, ACCURACY, RELIABILITY,
              AVAILABILITY, SECURITY, AND TITLE.</strong>
            </p>
            <p>
              AlecRae does not warrant that the Platform will be uninterrupted, error-free,
              secure, or free from viruses or other harmful components. AlecRae does not
              warrant that AI Output will be accurate, complete, current, reliable, or suitable
              for any particular purpose.
            </p>

            <h2>15. Dispute Resolution</h2>
            <h3>15.1 Governing Law</h3>
            <p>
              These Terms are governed by and construed in accordance with the laws of
              New Zealand, without regard to conflict of law principles. For users located in
              the United States, claims that are required by applicable law to be resolved
              under US federal or state law shall be governed by the laws of the State of
              Delaware and applicable US federal law.
            </p>
            <h3>15.2 Mandatory Arbitration (United States)</h3>
            <p>
              <strong>FOR USERS LOCATED IN THE UNITED STATES:</strong> Any dispute, claim, or
              controversy arising out of or relating to these Terms or your use of the Platform
              shall be resolved exclusively through binding arbitration administered by the
              American Arbitration Association (&ldquo;AAA&rdquo;) under its Commercial Arbitration Rules.
              The arbitration shall be conducted by a single arbitrator in Wilmington, Delaware.
              The arbitrator&rsquo;s decision shall be final and binding and may be entered as a
              judgment in any court of competent jurisdiction.
            </p>
            <h3>15.3 Class Action Waiver</h3>
            <p>
              <strong>YOU AGREE THAT ANY DISPUTE RESOLUTION PROCEEDINGS WILL BE CONDUCTED
              ONLY ON AN INDIVIDUAL BASIS AND NOT IN A CLASS, CONSOLIDATED, OR REPRESENTATIVE
              ACTION.</strong> If for any reason a claim proceeds in court rather than in
              arbitration, you waive any right to a jury trial.
            </p>
            <h3>15.4 Jurisdiction (Non-US Users)</h3>
            <p>
              For users located outside the United States, the courts of Auckland, New Zealand
              shall have exclusive jurisdiction over any dispute arising out of or in connection
              with these Terms, subject to mandatory consumer protection provisions in your
              jurisdiction that may confer jurisdiction on your local courts.
            </p>
            <h3>15.5 Time Limitation on Claims</h3>
            <p>
              Any cause of action or claim you may have arising out of or relating to these
              Terms or the Platform must be commenced within one (1) year after the cause of
              action accrues, or the claim is permanently barred. This limitation applies to
              the maximum extent permitted by applicable law.
            </p>

            <h2>16. Termination</h2>
            <h3>16.1 Termination by You</h3>
            <p>
              You may terminate your account at any time by contacting us at legal@alecrae.com
              or through your account settings. Termination does not entitle you to a refund
              of prepaid fees except where required by applicable consumer protection law.
            </p>
            <h3>16.2 Termination by AlecRae</h3>
            <p>
              AlecRae may suspend or terminate your access to the Platform immediately and
              without prior notice if: (a) you breach these Terms; (b) you fail to pay
              applicable fees; (c) your professional credentials are suspended, revoked, or
              expire; (d) we are required to do so by law or regulatory authority;
              (e) continued provision of the Platform to you is no longer commercially
              viable; or (f) your use of the Platform poses a security risk or risk of harm
              to other users.
            </p>
            <h3>16.3 Effect of Termination</h3>
            <p>
              Upon termination: (a) your right to access and use the Platform ceases
              immediately; (b) you must cease all use of AlecRae IP; (c) AlecRae will
              provide a reasonable period (not less than 30 days) for you to export your
              Content and Client Data; (d) after the export period, AlecRae will delete your
              Content and Client Data in accordance with our data retention policy, except as
              required by law or for legitimate legal hold purposes.
            </p>
            <p>
              The following sections survive termination: Sections 4 (Tool Not Provider),
              5 (AI Output), 8 (Intellectual Property), 12 (Limitation of Liability),
              13 (Indemnification), 14 (Disclaimer of Warranties), 15 (Dispute Resolution),
              and 17 (General Provisions).
            </p>

            <h2>17. General Provisions</h2>
            <h3>17.1 Entire Agreement</h3>
            <p>
              These Terms, together with the Privacy Policy, Acceptable Use Policy, and
              Disclaimer, constitute the entire agreement between you and AlecRae with respect
              to your use of the Platform and supersede all prior or contemporaneous
              communications, representations, and agreements, whether oral or written.
            </p>
            <h3>17.2 Severability</h3>
            <p>
              If any provision of these Terms is held to be invalid, illegal, or unenforceable
              by a court of competent jurisdiction, the remaining provisions shall continue in
              full force and effect. The invalid provision shall be modified to the minimum
              extent necessary to make it valid and enforceable while preserving its original
              intent.
            </p>
            <h3>17.3 Waiver</h3>
            <p>
              No waiver of any provision of these Terms shall be deemed a further or continuing
              waiver of such provision or any other provision. AlecRae&rsquo;s failure to assert
              any right or provision under these Terms shall not constitute a waiver of such
              right or provision.
            </p>
            <h3>17.4 Assignment</h3>
            <p>
              You may not assign or transfer these Terms or any rights or obligations hereunder
              without AlecRae&rsquo;s prior written consent. AlecRae may assign these Terms
              without restriction, including in connection with a merger, acquisition,
              corporate reorganisation, or sale of all or substantially all of its assets.
            </p>
            <h3>17.5 Force Majeure</h3>
            <p>
              AlecRae shall not be liable for any delay or failure to perform its obligations
              under these Terms due to causes beyond its reasonable control, including but not
              limited to acts of God, natural disasters, war, terrorism, riots, embargoes,
              acts of governmental authorities, epidemics, pandemics, power failures,
              telecommunications failures, internet disruptions, cyberattacks, or failures
              of third-party service providers.
            </p>
            <h3>17.6 Notices</h3>
            <p>
              All notices to AlecRae must be sent to legal@alecrae.com or by post to AlecRae
              Ltd, Auckland, New Zealand. Notices to you will be sent to the email address
              associated with your account. Notices are deemed received upon delivery for
              email and five (5) business days after posting for physical mail.
            </p>
            <h3>17.7 Amendments</h3>
            <p>
              AlecRae reserves the right to modify these Terms at any time. Material changes
              will be notified via email or prominent notice on the Platform at least 30 days
              before they take effect. Your continued use of the Platform after the effective
              date of any modification constitutes your acceptance of the modified Terms.
              If you do not agree to the modified Terms, you must discontinue use of the
              Platform before the effective date.
            </p>
            <h3>17.8 Third-Party Beneficiaries</h3>
            <p>
              These Terms do not create any third-party beneficiary rights. No third party
              (including your clients) may enforce any provision of these Terms.
            </p>
            <h3>17.9 Headings</h3>
            <p>
              Section headings are for convenience only and do not affect the interpretation
              of these Terms.
            </p>
            <h3>17.10 Language</h3>
            <p>
              These Terms are drafted in the English language. If these Terms are translated
              into any other language, the English language version shall prevail in the event
              of any conflict or inconsistency.
            </p>

            <h2>18. Contact Information</h2>
            <p>
              For questions about these Terms, contact us at:
            </p>
            <p>
              <strong>AlecRae Ltd</strong><br />
              Auckland, New Zealand<br />
              Email: legal@alecrae.com<br />
              Web: {BRAND.url}
            </p>

          </div>
        </Container>
      </section>
    </>
  );
}
