import type { Metadata } from "next";
import Container from "@/app/components/shared/Container";
import Reveal from "@/app/components/effects/Reveal";

export const metadata: Metadata = {
  title: "Terms of Service",
  description:
    "Marco Reid terms of service. The binding agreement between you and Reid & Associates Ltd.",
};

const sections = [
  {
    title: "1. Definitions",
    content:
      '"Agreement" means these Terms of Service, the Privacy Policy, the Acceptable Use Policy, and any order forms or addenda executed between the parties. "Platform" means the Marco Reid web application, APIs, and all related services. "User" or "you" means the individual or entity accessing or using the Platform. "We", "us", or "Marco Reid" means Reid & Associates Ltd, a company registered in New Zealand. "Content" means any data, text, files, documents, audio, or other materials uploaded to or generated through the Platform. "User Content" means Content uploaded or created by you. "AI Output" means any content, research results, citations, summaries, or other materials generated by the Marco research engine or any other AI-powered feature of the Platform. "Subscription" means your paid access to the Platform under a specific tier. "Professional" means a licensed attorney, accountant, or other credentialled practitioner using the Platform. "Client Data" means any information relating to your clients that you store, process, or transmit through the Platform, including but not limited to matter details, trust account records, documents, and communications.',
  },
  {
    title: "2. Acceptance and eligibility",
    content:
      "By accessing or using the Platform, you confirm that you have read, understood, and agree to be bound by this Agreement. If you are accepting on behalf of a company, firm, or other legal entity, you represent that you have authority to bind that entity. If you do not agree, you must not use the Platform. You must be at least 18 years of age and legally capable of entering into binding contracts in your jurisdiction. If you are a legal or accounting professional, you represent that you hold valid credentials in your jurisdiction of practice and that your use of the Platform complies with your professional obligations, rules of conduct, and ethical duties.",
  },
  {
    title: "3. Description of service",
    content:
      "Marco Reid provides AI-powered practice management tools for legal and accounting professionals. The Platform includes: (a) matter and case management, (b) client relationship management, (c) document management, (d) time tracking and billing, (e) trust account management (IOLTA-compliant ledger), (f) Marco — an AI-powered cross-domain research engine covering legal, accounting, tax, and intellectual property research with citation verification, (g) Marco Reid Voice — professional dictation with legal and accounting vocabulary, (h) a professional marketplace enabling inter-professional collaboration and billing via Stripe Connect, and (i) court technology tools. Features may vary by subscription tier and may be modified, added, or deprecated at our discretion with reasonable notice.",
  },
  {
    title: "4. Account registration and security",
    content:
      "You must register an account to access the Platform. You agree to provide accurate, current, and complete registration information and to update it as necessary. You are solely responsible for maintaining the confidentiality of your account credentials. You must use a strong, unique password and must not share your credentials with any person. You must notify us immediately at security@marcoreid.com if you become aware of any unauthorised use of your account or any security breach. We are not liable for any loss or damage arising from your failure to protect your account credentials. We may suspend or terminate accounts that we reasonably believe have been compromised.",
  },
  {
    title: "5. Marco AI research — critical disclaimers",
    content:
      'MARCO IS AN AI-POWERED RESEARCH ASSISTANT. IT IS NOT A LAWYER, ACCOUNTANT, TAX ADVISER, OR LICENSED PROFESSIONAL OF ANY KIND. AI Output does not constitute legal advice, tax advice, financial advice, accounting advice, or professional advice of any kind. AI Output does not create, and must not be construed as creating, an attorney-client relationship, accountant-client relationship, or any professional-client relationship between you and Reid & Associates Ltd. While we implement citation verification against authoritative public-domain sources (including CourtListener, Cornell LII, GovInfo, IRS.gov, and others), AI-generated content may contain errors, omissions, hallucinations, outdated information, or mischaracterisations of law, regulation, or precedent. Citations marked "VERIFIED" mean only that we located a matching record in a public database — not that the citation is correctly applied to your legal question or that the underlying law remains good law. YOU ARE SOLELY AND EXCLUSIVELY RESPONSIBLE FOR: (a) independently verifying all AI Output before relying on it, (b) confirming the current validity and applicability of all citations, cases, statutes, regulations, and rulings, (c) exercising your own professional judgement in all matters, (d) ensuring compliance with your jurisdiction\'s rules of professional conduct, and (e) all decisions made and actions taken based on AI Output. No AI Output should be cited in any court filing, legal document, tax return, financial statement, or professional communication without independent verification by a qualified professional. Reid & Associates Ltd expressly disclaims all liability for any reliance on AI Output.',
  },
  {
    title: "6. Voice dictation",
    content:
      "Marco Reid Voice uses third-party speech-to-text services (currently OpenAI Whisper) to transcribe audio. Audio data is transmitted to the third-party provider for processing and is subject to their terms and privacy policies. We do not guarantee transcription accuracy. You are responsible for reviewing and correcting all transcriptions before use. You must not dictate content that violates applicable law or the rights of any third party. You acknowledge that voice data may be processed in jurisdictions outside your own.",
  },
  {
    title: "7. Professional marketplace",
    content:
      "The Platform includes a marketplace enabling professionals to offer services and process payments through Stripe Connect. Reid & Associates Ltd acts solely as a technology intermediary and is not a party to any transaction between professionals or between professionals and their clients. We charge a platform fee (currently 10%) on marketplace transactions. Payment processing is handled by Stripe and is subject to Stripe's terms of service and connected account agreement. We are not responsible for the quality, legality, or delivery of any services offered through the marketplace. Disputes between marketplace participants must be resolved between the parties directly.",
  },
  {
    title: "8. Trust accounts and IOLTA compliance",
    content:
      "The Platform provides trust account ledger functionality to assist with IOLTA and client trust accounting. This functionality is a record-keeping tool only. You remain solely responsible for compliance with all trust accounting rules, regulations, and ethical obligations in your jurisdiction, including but not limited to proper segregation of client funds, timely deposits, authorised disbursements, and recordkeeping requirements. Reid & Associates Ltd does not hold, custody, or control any client funds. The Platform does not replace your obligation to maintain compliant trust accounts with authorised financial institutions. Any discrepancy between Platform records and your bank records must be investigated and resolved by you.",
  },
  {
    title: "9. Acceptable use",
    content:
      "You agree to comply with our Acceptable Use Policy, which is incorporated by reference. Without limitation, you must not: (a) use the Platform to violate any law, regulation, or professional rule of conduct; (b) upload or transmit any malware, virus, or harmful code; (c) attempt to gain unauthorised access to any part of the Platform or its infrastructure; (d) use the Platform to infringe, misappropriate, or violate any intellectual property or proprietary right; (e) reverse-engineer, decompile, or disassemble any part of the Platform; (f) use automated tools to scrape, crawl, or extract data from the Platform; (g) resell, sublicence, or redistribute access to the Platform without written consent; (h) impersonate any person or entity; (i) use AI Output to generate misleading legal citations or fabricated authorities; or (j) use the Platform in any manner that could damage, disable, overburden, or impair its operation.",
  },
  {
    title: "10. Intellectual property",
    content:
      'The Platform, including its source code, design, architecture, documentation, trademarks, and all proprietary technology, is the exclusive property of Reid & Associates Ltd and is protected by copyright, trademark, trade secret, and other intellectual property laws of New Zealand and international treaties. "Marco Reid", "Marco", "The Oracle", and associated logos are trademarks of Reid & Associates Ltd. You are granted a limited, non-exclusive, non-transferable, revocable licence to access and use the Platform solely for your internal business purposes during your active Subscription. You retain all rights to your User Content. By uploading User Content, you grant us a limited, non-exclusive licence to process, store, and transmit that Content solely as necessary to provide the Platform services. We do not claim ownership of your User Content or Client Data.',
  },
  {
    title: "11. Data processing and privacy",
    content:
      "Your use of the Platform is subject to our Privacy Policy, which describes how we collect, use, store, and protect your information. To the extent that we process personal data on your behalf as a data processor, the terms of our Data Processing Agreement apply. You are responsible for obtaining all necessary consents from your clients and other data subjects before uploading their personal data to the Platform. You represent that your use of the Platform complies with all applicable data protection laws, including the GDPR, NZ Privacy Act 2020, Australian Privacy Act, UK GDPR, and CCPA as applicable.",
  },
  {
    title: "12. Payment, billing, and taxes",
    content:
      "Paid Subscriptions are billed in advance on a monthly basis via Stripe. All fees are quoted in USD unless otherwise specified. You authorise us to charge your designated payment method for all applicable fees. Prices are listed on our pricing page and may change with at least 30 days' written notice. Fee increases take effect at your next billing cycle following the notice period. All fees are exclusive of taxes. You are responsible for all applicable taxes, duties, and levies imposed by your jurisdiction. Overdue payments accrue interest at 1.5% per month or the maximum rate permitted by law, whichever is lower. We may suspend access for accounts with payments overdue by more than 14 days.",
  },
  {
    title: "13. Refunds and cancellation",
    content:
      "You may cancel your Subscription at any time from your account settings or by contacting us. Cancellation takes effect at the end of your current billing period — you retain access until then. We offer a 14-day refund window from the date of your initial Subscription purchase. After 14 days, fees are non-refundable except where required by applicable consumer protection law. If you are a New Zealand consumer, nothing in this section limits your rights under the Consumer Guarantees Act 1993.",
  },
  {
    title: "14. Warranty disclaimers",
    content:
      'THE PLATFORM IS PROVIDED "AS IS" AND "AS AVAILABLE" WITHOUT WARRANTIES OF ANY KIND, WHETHER EXPRESS, IMPLIED, STATUTORY, OR OTHERWISE. TO THE MAXIMUM EXTENT PERMITTED BY APPLICABLE LAW, WE DISCLAIM ALL WARRANTIES, INCLUDING IMPLIED WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, NON-INFRINGEMENT, AND ACCURACY. WE DO NOT WARRANT THAT: (a) THE PLATFORM WILL BE UNINTERRUPTED, ERROR-FREE, OR SECURE; (b) AI OUTPUT WILL BE ACCURATE, COMPLETE, OR CURRENT; (c) THE PLATFORM WILL MEET YOUR SPECIFIC REQUIREMENTS; OR (d) DEFECTS WILL BE CORRECTED WITHIN ANY PARTICULAR TIMEFRAME. NO ADVICE OR INFORMATION OBTAINED THROUGH THE PLATFORM CREATES ANY WARRANTY NOT EXPRESSLY STATED HEREIN. Some jurisdictions do not allow the exclusion of certain warranties. In those jurisdictions, the exclusions above apply only to the extent permitted by law.',
  },
  {
    title: "15. Limitation of liability",
    content:
      "TO THE MAXIMUM EXTENT PERMITTED BY LAW: (a) REID & ASSOCIATES LTD, ITS DIRECTORS, OFFICERS, EMPLOYEES, AGENTS, AND AFFILIATES SHALL NOT BE LIABLE FOR ANY INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL, EXEMPLARY, OR PUNITIVE DAMAGES, INCLUDING BUT NOT LIMITED TO LOSS OF PROFITS, REVENUE, DATA, BUSINESS OPPORTUNITIES, GOODWILL, OR ANTICIPATED SAVINGS, REGARDLESS OF THE CAUSE OF ACTION OR THEORY OF LIABILITY, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGES; (b) OUR TOTAL AGGREGATE LIABILITY ARISING OUT OF OR RELATING TO THIS AGREEMENT SHALL NOT EXCEED THE GREATER OF: (i) THE TOTAL FEES PAID BY YOU IN THE TWELVE (12) MONTHS IMMEDIATELY PRECEDING THE EVENT GIVING RISE TO THE CLAIM, OR (ii) ONE HUNDRED NEW ZEALAND DOLLARS (NZD $100); AND (c) WE SHALL HAVE NO LIABILITY WHATSOEVER FOR ANY LOSS, DAMAGE, OR CLAIM ARISING FROM: (i) YOUR RELIANCE ON AI OUTPUT, (ii) ERRORS OR OMISSIONS IN AI-GENERATED CITATIONS OR RESEARCH, (iii) YOUR FAILURE TO INDEPENDENTLY VERIFY AI OUTPUT, (iv) ACTIONS TAKEN BY YOUR CLIENTS BASED ON INFORMATION DERIVED FROM THE PLATFORM, OR (v) YOUR FAILURE TO COMPLY WITH PROFESSIONAL RULES OF CONDUCT. Some jurisdictions do not allow certain limitations of liability. In those jurisdictions, the limitations above apply to the maximum extent permitted by law. Nothing in this Agreement excludes or limits liability for death or personal injury caused by negligence, fraud, or any other liability that cannot be excluded by law.",
  },
  {
    title: "16. Indemnification",
    content:
      "You agree to indemnify, defend, and hold harmless Reid & Associates Ltd, its directors, officers, employees, agents, and affiliates from and against any and all claims, losses, damages, liabilities, costs, and expenses (including reasonable legal fees) arising out of or related to: (a) your use of the Platform; (b) your violation of this Agreement; (c) your violation of any applicable law, regulation, or professional rule of conduct; (d) your User Content or Client Data; (e) your reliance on AI Output without independent verification; (f) any claim by a third party (including your clients) arising from services you provided using or in reliance on the Platform; (g) your use of the professional marketplace; or (h) your failure to comply with trust accounting, IOLTA, or other fiduciary obligations. This indemnification obligation survives termination of this Agreement.",
  },
  {
    title: "17. Dispute resolution and governing law",
    content:
      'This Agreement is governed by and construed in accordance with the laws of New Zealand, without regard to conflict of law principles. Any dispute arising out of or relating to this Agreement that cannot be resolved through good-faith negotiation within thirty (30) days shall be submitted to binding arbitration administered by the New Zealand Dispute Resolution Centre under its commercial arbitration rules. The arbitration shall be conducted in Auckland, New Zealand, in English, by a single arbitrator. The arbitrator\'s decision shall be final and binding and may be entered as a judgement in any court of competent jurisdiction. YOU AGREE THAT ANY DISPUTE RESOLUTION PROCEEDINGS WILL BE CONDUCTED ONLY ON AN INDIVIDUAL BASIS AND NOT IN A CLASS, CONSOLIDATED, OR REPRESENTATIVE ACTION. Notwithstanding the foregoing, either party may seek injunctive or equitable relief in any court of competent jurisdiction to protect its intellectual property rights or confidential information. Nothing in this section limits your rights under the Consumer Guarantees Act 1993 (NZ) or any other mandatory consumer protection law.',
  },
  {
    title: "18. Termination",
    content:
      "Either party may terminate this Agreement at any time by providing written notice. We may suspend or terminate your access immediately and without notice if: (a) you breach this Agreement; (b) your payment is overdue by more than 14 days; (c) we reasonably believe your account has been compromised; or (d) we are required to do so by law. Upon termination: (i) your licence to use the Platform ceases immediately; (ii) you have 30 days to export your data using the Platform's export functionality or by contacting us; (iii) after 30 days, we will permanently delete your User Content and Client Data, except where retention is required by law or for legitimate record-keeping; and (iv) accrued payment obligations and the following sections survive termination: Sections 5, 10, 14, 15, 16, 17, and 20.",
  },
  {
    title: "19. Modifications to terms",
    content:
      "We may modify these Terms from time to time. Material changes will be communicated to registered users via email at least thirty (30) days before they take effect. Non-material changes (such as clarifications or formatting) may take effect immediately upon posting. Your continued use of the Platform after changes take effect constitutes acceptance of the modified Terms. If you do not agree to the modified Terms, you must discontinue use and may terminate your account.",
  },
  {
    title: "20. General provisions",
    content:
      'Entire Agreement: This Agreement, together with the Privacy Policy, Acceptable Use Policy, and any executed order forms, constitutes the entire agreement between you and Reid & Associates Ltd and supersedes all prior agreements. Severability: If any provision is held invalid or unenforceable, the remaining provisions remain in full force and effect, and the invalid provision shall be modified to the minimum extent necessary to make it valid and enforceable. Assignment: You may not assign this Agreement without our prior written consent. We may assign this Agreement in connection with a merger, acquisition, or sale of all or substantially all of our assets. Waiver: Our failure to enforce any right or provision shall not constitute a waiver of that right or provision. Force Majeure: Neither party shall be liable for delays or failures in performance resulting from causes beyond its reasonable control, including natural disasters, war, terrorism, pandemic, government actions, or failures of third-party infrastructure. Notices: All notices under this Agreement shall be in writing and delivered by email to the addresses associated with your account (for notices to you) or to legal@marcoreid.com (for notices to us). Export Compliance: You represent that you are not located in a country subject to embargo and that you are not on any sanctioned parties list. Headings: Section headings are for convenience only and have no legal effect.',
  },
];

export default function TermsPage() {
  return (
    <>
      <section className="bg-navy-500 pt-32 pb-20 sm:pt-40 sm:pb-28">
        <Container className="text-center">
          <h1 className="font-serif text-hero text-white">
            Terms of Service
          </h1>
          <p className="mx-auto mt-6 max-w-xl text-xl text-navy-200">
            The binding agreement between you and Marco Reid.
          </p>
        </Container>
      </section>

      <section className="py-24 sm:py-36">
        <Container>
          <div className="mx-auto max-w-3xl">
            <Reveal>
              <p className="text-sm text-navy-400">
                Last updated: April 2026
              </p>
              <p className="mt-6 text-lg text-navy-500">
                These Terms of Service (&ldquo;Terms&rdquo; or
                &ldquo;Agreement&rdquo;) govern your access to and use of the
                Marco Reid platform operated by Reid &amp; Associates Ltd, a
                company incorporated in New Zealand (NZBN pending). By using the
                Platform, you enter into a legally binding contract with Reid
                &amp; Associates Ltd.
              </p>
              <p className="mt-4 text-lg font-semibold text-navy-700">
                PLEASE READ THESE TERMS CAREFULLY. THEY CONTAIN A BINDING
                ARBITRATION CLAUSE, A CLASS ACTION WAIVER, AND LIMITATIONS OF
                LIABILITY THAT AFFECT YOUR LEGAL RIGHTS.
              </p>
            </Reveal>

            <div className="mt-16 space-y-12">
              {sections.map((section, i) => (
                <Reveal key={section.title} delay={i * 0.05}>
                  <h2 className="font-serif text-headline text-navy-800">
                    {section.title}
                  </h2>
                  <p className="mt-4 text-lg leading-relaxed text-navy-500 whitespace-pre-line">
                    {section.content}
                  </p>
                </Reveal>
              ))}
            </div>

            <Reveal delay={0.2}>
              <div className="mt-16 rounded-2xl border border-navy-100 bg-navy-50 p-8">
                <p className="font-serif text-xl text-navy-700">
                  Questions about these terms?
                </p>
                <p className="mt-2 text-navy-400">
                  Contact us at legal@marcoreid.com or write to Reid &amp;
                  Associates Ltd, Auckland, New Zealand.
                </p>
              </div>
            </Reveal>
          </div>
        </Container>
      </section>
    </>
  );
}
