import type { Metadata } from "next";
import Container from "@/app/components/shared/Container";
import Reveal from "@/app/components/effects/Reveal";

export const metadata: Metadata = {
  title: "DMCA & Copyright Policy",
  description:
    "Marco Reid DMCA and copyright policy. How to report intellectual property infringement.",
};

const sections = [
  {
    title: "1. Respect for intellectual property",
    content:
      "Reid & Associates Ltd (\"Marco Reid\") respects the intellectual property rights of others and expects all users to do the same. We comply with the Digital Millennium Copyright Act (DMCA), the New Zealand Copyright Act 1994, and other applicable intellectual property laws. We will respond promptly to notices of alleged copyright infringement that comply with applicable law.",
  },
  {
    title: "2. Reporting copyright infringement",
    content:
      "If you believe that content available on or through the Marco Reid platform infringes your copyright, you may submit a DMCA takedown notice to our designated agent. Your notice must include: (a) a physical or electronic signature of the copyright owner or a person authorised to act on their behalf; (b) identification of the copyrighted work claimed to have been infringed; (c) identification of the material that is claimed to be infringing and its location on the Platform, with sufficient detail for us to locate it; (d) your contact information, including name, address, telephone number, and email; (e) a statement that you have a good faith belief that use of the material in the manner complained of is not authorised by the copyright owner, its agent, or the law; and (f) a statement, under penalty of perjury, that the information in the notice is accurate and that you are the copyright owner or authorised to act on their behalf.",
  },
  {
    title: "3. Designated agent",
    content:
      "DMCA notices should be sent to our designated agent:\n\nAttention: DMCA Agent\nReid & Associates Ltd\nAuckland, New Zealand\nEmail: legal@marcoreid.com\nSubject line: \"DMCA Takedown Notice\"\n\nPlease note: sending a DMCA notice is a legal action. Misrepresentation of facts in a DMCA notice may result in liability for damages, including costs and legal fees.",
  },
  {
    title: "4. Counter-notification",
    content:
      "If you believe your content was removed or disabled as a result of mistake or misidentification, you may submit a counter-notification to our designated agent. Your counter-notification must include: (a) your physical or electronic signature; (b) identification of the material that was removed and its location before removal; (c) a statement under penalty of perjury that you have a good faith belief the material was removed by mistake or misidentification; (d) your name, address, and telephone number; and (e) a statement that you consent to the jurisdiction of the courts of Auckland, New Zealand (or, if you are outside New Zealand, any judicial district in which Reid & Associates Ltd may be found), and that you will accept service of process from the person who submitted the DMCA notice or their agent. If we receive a valid counter-notification, we will forward it to the original complainant and restore the removed material within 10 to 14 business days unless the complainant notifies us of a court action.",
  },
  {
    title: "5. Repeat infringers",
    content:
      "In accordance with the DMCA and our Terms of Service, we will terminate the accounts of users who are repeat copyright infringers in appropriate circumstances. We may also terminate accounts of users who infringe intellectual property rights even for a single offence in serious cases.",
  },
  {
    title: "6. AI-generated content",
    content:
      "AI Output generated by the Marco research engine may include summaries, analysis, or excerpts from publicly available legal materials. Such use is intended to be transformative and within the bounds of fair use (US), fair dealing (NZ/UK/AU), and equivalent doctrines. If you believe that AI Output infringes your copyright, please contact us using the procedure in Section 2. We will investigate promptly and take appropriate action.",
  },
  {
    title: "7. Other intellectual property claims",
    content:
      "If you believe that content on the Platform infringes your trademark, patent, trade secret, or other intellectual property right (not copyright), please contact us at legal@marcoreid.com with a detailed description of the alleged infringement. We will investigate and respond appropriately.",
  },
];

export default function DmcaPage() {
  return (
    <>
      <section className="bg-navy-500 pt-32 pb-20 sm:pt-40 sm:pb-28">
        <Container className="text-center">
          <h1 className="font-serif text-hero text-white">
            DMCA &amp; Copyright Policy
          </h1>
          <p className="mx-auto mt-6 max-w-xl text-xl text-navy-200">
            How we handle intellectual property claims.
          </p>
        </Container>
      </section>

      <section className="py-24 sm:py-36">
        <Container>
          <div className="mx-auto max-w-3xl">
            <Reveal>
              <p className="text-sm text-navy-400">
                Last updated: April 2026
              </p>
              <p className="mt-6 text-lg text-navy-500">
                This policy describes how Reid &amp; Associates Ltd handles
                copyright and other intellectual property claims related to the
                Marco Reid platform.
              </p>
            </Reveal>

            <div className="mt-16 space-y-12">
              {sections.map((section, i) => (
                <Reveal key={section.title} delay={i * 0.05}>
                  <h2 className="font-serif text-headline text-navy-800">
                    {section.title}
                  </h2>
                  <p className="mt-4 text-lg leading-relaxed text-navy-500 whitespace-pre-line">
                    {section.content}
                  </p>
                </Reveal>
              ))}
            </div>

            <Reveal delay={0.2}>
              <div className="mt-16 rounded-2xl border border-navy-100 bg-navy-50 p-8">
                <p className="font-serif text-xl text-navy-700">
                  Need to report an infringement?
                </p>
                <p className="mt-2 text-navy-400">
                  Contact our DMCA Agent at legal@marcoreid.com with the subject
                  line &ldquo;DMCA Takedown Notice&rdquo;.
                </p>
              </div>
            </Reveal>
          </div>
        </Container>
      </section>
    </>
  );
}
