export type Locale = "en" | "fr";

export const translations: Record<Locale, Record<string, string>> = {
  en: {
    // Navigation
    "nav.legal": "Legal",
    "nav.accounting": "Accounting",
    "nav.courtroom": "Courtroom",
    "nav.marco": "Marco",
    "nav.voice": "Voice",
    "nav.pricing": "Pricing",
    "nav.bookDemo": "Book a Demo",
    "nav.signIn": "Sign in",

    // Dashboard
    "dashboard.welcome": "Welcome back",
    "dashboard.activeMatters": "Active matters",
    "dashboard.hoursThisWeek": "Hours this week",
    "dashboard.revenue": "Revenue (month)",
    "dashboard.trustBalance": "Trust balance",
    "dashboard.deadlines": "Upcoming deadlines",
    "dashboard.askMarco": "Ask Marco",
    "dashboard.newMatter": "New matter",
    "dashboard.newClient": "New client",
    "dashboard.logTime": "Log time",

    // Matters
    "matters.title": "Matters",
    "matters.new": "New matter",
    "matters.active": "Active",
    "matters.onHold": "On hold",
    "matters.closed": "Closed",

    // Clients
    "clients.title": "Clients",
    "clients.new": "New client",

    // Documents
    "documents.title": "Documents",
    "documents.upload": "Upload document",
    "documents.newDoc": "New document",

    // Trust
    "trust.title": "Trust accounts",
    "trust.deposit": "Deposit",
    "trust.withdrawal": "Withdrawal",
    "trust.feeDraw": "Fee draw",

    // Common
    "common.save": "Save",
    "common.cancel": "Cancel",
    "common.delete": "Delete",
    "common.edit": "Edit",
    "common.search": "Search",
    "common.filter": "Filter",
    "common.export": "Export",
    "common.back": "Back",
    "common.loading": "Loading...",
    "common.noResults": "No results found",

    // Legal
    "legal.privacyPolicy": "Privacy Policy",
    "legal.termsOfService": "Terms of Service",
    "legal.cookiePolicy": "Cookie Policy",

    // Footer
    "footer.company": "Company",
    "footer.products": "Products",
    "footer.resources": "Resources",
    "footer.legal": "Legal",
    "footer.allRights": "All rights reserved",

    // AI
    "ai.disclaimer":
      "This content is generated by AI for research and informational purposes only. It does not constitute legal advice, tax advice, or professional advice of any kind.",
    "ai.askMarco": "What would you like to research today?",
    "ai.verified": "Verified",
    "ai.unverified": "Unverified",
    "ai.notFound": "Not found",
  },
  fr: {
    // Navigation
    "nav.legal": "Juridique",
    "nav.accounting": "Comptabilité",
    "nav.courtroom": "Tribunal",
    "nav.marco": "Marco",
    "nav.voice": "Voix",
    "nav.pricing": "Tarifs",
    "nav.bookDemo": "Réserver une démo",
    "nav.signIn": "Se connecter",

    // Dashboard
    "dashboard.welcome": "Bon retour",
    "dashboard.activeMatters": "Dossiers actifs",
    "dashboard.hoursThisWeek": "Heures cette semaine",
    "dashboard.revenue": "Revenus (mois)",
    "dashboard.trustBalance": "Solde fiduciaire",
    "dashboard.deadlines": "Échéances à venir",
    "dashboard.askMarco": "Demander à Marco",
    "dashboard.newMatter": "Nouveau dossier",
    "dashboard.newClient": "Nouveau client",
    "dashboard.logTime": "Saisir le temps",

    // Matters
    "matters.title": "Dossiers",
    "matters.new": "Nouveau dossier",
    "matters.active": "Actif",
    "matters.onHold": "En attente",
    "matters.closed": "Fermé",

    // Clients
    "clients.title": "Clients",
    "clients.new": "Nouveau client",

    // Documents
    "documents.title": "Documents",
    "documents.upload": "Téléverser un document",
    "documents.newDoc": "Nouveau document",

    // Trust
    "trust.title": "Comptes en fiducie",
    "trust.deposit": "Dépôt",
    "trust.withdrawal": "Retrait",
    "trust.feeDraw": "Prélèvement d’honoraires",

    // Common
    "common.save": "Enregistrer",
    "common.cancel": "Annuler",
    "common.delete": "Supprimer",
    "common.edit": "Modifier",
    "common.search": "Rechercher",
    "common.filter": "Filtrer",
    "common.export": "Exporter",
    "common.back": "Retour",
    "common.loading": "Chargement...",
    "common.noResults": "Aucun résultat trouvé",

    // Legal
    "legal.privacyPolicy": "Politique de confidentialité",
    "legal.termsOfService": "Conditions d’utilisation",
    "legal.cookiePolicy": "Politique de témoins",

    // Footer
    "footer.company": "Entreprise",
    "footer.products": "Produits",
    "footer.resources": "Ressources",
    "footer.legal": "Mentions légales",
    "footer.allRights": "Tous droits réservés",

    // AI
    "ai.disclaimer":
      "Ce contenu est généré par l’IA à des fins de recherche et d’information uniquement. Il ne constitue pas un avis juridique, fiscal ou professionnel de quelque nature que ce soit.",
    "ai.askMarco": "Que souhaitez-vous rechercher aujourd’hui ?",
    "ai.verified": "Vérifié",
    "ai.unverified": "Non vérifié",
    "ai.notFound": "Non trouvé",
  },
};

export function t(key: string, locale: Locale = "en"): string {
  return translations[locale]?.[key] ?? translations.en[key] ?? key;
}

export function getLocaleFromJurisdiction(jurisdiction: string): Locale {
  // Quebec defaults to French
  if (jurisdiction === "CA-QC" || jurisdiction === "QC") return "fr";
  return "en";
}
