export const DISCLAIMERS = {
  // Core AI disclaimer - appears on every AI output
  AI_RESEARCH:
    "This content is generated by artificial intelligence for research and informational purposes only. It does not constitute legal advice, tax advice, accounting advice, or professional advice of any kind. It does not create an attorney-client, accountant-client, or any other professional-client relationship. AI-generated content may contain errors, omissions, or hallucinations despite our verification systems. Always verify AI-generated content independently before any reliance. Marco Reid is a tool for licensed professionals — it is not a substitute for professional judgment, training, or expertise.",

  // Trust accounting disclaimer
  TRUST_ACCOUNTING:
    "Marco Reid's trust accounting features are tools to assist licensed professionals in managing client trust funds. They do not guarantee compliance with your jurisdiction's trust accounting rules. It remains your sole professional responsibility to ensure compliance with all applicable trust accounting regulations, including but not limited to IOLTA rules (US), SRA Accounts Rules 2019 (UK), Law Society Trust Account Regulations (NZ), Legal Profession Uniform Law (AU), and provincial Law Society rules (CA). Marco Reid accepts no liability for trust accounting errors, misappropriation, or regulatory non-compliance.",

  // E-signature disclaimer
  ESIGNATURE:
    "Marco Reid's e-signature tracking features record signature workflow status. They do not independently verify signer identity, legal capacity, or the enforceability of electronically signed documents in your jurisdiction. Enforceability of electronic signatures varies by jurisdiction, document type, and applicable law. Consult qualified legal counsel regarding the validity of electronic signatures for your specific use case.",

  // Tax/accounting disclaimer
  TAX_FILING:
    "Marco Reid's tax calculation and filing preparation tools provide estimates based on publicly available tax rates and rules. They are not a substitute for professional tax advice. Tax laws change frequently and may vary by specific circumstances. All tax filings prepared using Marco Reid must be reviewed and approved by a qualified, licensed tax professional before submission. Marco Reid accepts no liability for incorrect tax calculations, missed deadlines, penalties, or interest resulting from reliance on platform calculations.",

  // Payroll disclaimer
  PAYROLL:
    "Payroll calculations are estimates based on current published tax rates and contribution schedules. Actual amounts may vary based on individual circumstances, elections, exemptions, and rate changes. All payroll runs must be reviewed by a qualified payroll professional. Marco Reid is not a registered payroll bureau and does not file payroll returns on your behalf unless explicitly engaged through a licensed tax agent.",

  // Court filing disclaimer
  COURT_FILING:
    "Marco Reid's court e-filing features assist in document preparation and submission tracking. Filing deadlines, formatting requirements, and procedural rules vary by jurisdiction and court. It is your sole professional responsibility to verify all deadlines, comply with all local rules, and ensure filings meet court requirements. Marco Reid accepts no liability for missed deadlines, rejected filings, or procedural errors.",

  // Conflicts disclaimer
  CONFLICTS:
    "Marco Reid's conflict checking searches your existing client and matter database only. It does not search external databases, court records, or prior firm records not entered into the system. A clear result does not guarantee the absence of a conflict of interest. It remains your sole professional and ethical obligation to conduct thorough conflict checks as required by your jurisdiction's rules of professional conduct.",

  // Regulatory alerts disclaimer
  REGULATORY_ALERTS:
    "Regulatory change alerts are provided for informational awareness only. They may not capture all relevant changes, may be delayed, and may not reflect the final form of enacted legislation. Do not rely solely on Marco Reid alerts for regulatory compliance. Consult official government sources and qualified professional advisors for compliance decisions.",

  // Audit trail disclaimer
  AUDIT_TRAIL:
    "Marco Reid's audit trail system creates an immutable, cryptographically-chained record of platform activity. Each event is hashed using SHA-256 and linked to the previous event, creating a tamper-evident chain that can be independently verified. Audit records cannot be modified or deleted. This system is designed to support compliance with professional regulation, trust accounting audit requirements, and court discovery obligations across all operating jurisdictions. The audit trail records platform-level actions only — it does not constitute a complete record of all professional communications or actions taken outside the platform.",

  // General platform disclaimer - shows on signup/terms
  PLATFORM:
    "Marco Reid is a software platform providing tools for licensed legal and accounting professionals. It is not a law firm, accounting firm, tax agency, or professional services provider. No professional-client relationship is created by use of this platform. The platform does not provide legal advice, tax advice, or professional opinions. All outputs, calculations, research results, and recommendations must be independently verified by a qualified professional before any reliance or action.",
} as const;

// Jurisdiction-specific liability limitations
export const LIABILITY_CAPS: Record<string, string> = {
  NZ: "To the maximum extent permitted by the New Zealand Consumer Guarantees Act 1993 and the Fair Trading Act 1986, Marco Reid's total aggregate liability for any claims arising from or relating to your use of the platform shall not exceed the total fees paid by you in the twelve (12) months immediately preceding the claim.",
  AU: "To the maximum extent permitted by the Australian Consumer Law (Schedule 2 of the Competition and Consumer Act 2010), Marco Reid's total aggregate liability shall not exceed the total fees paid by you in the twelve (12) months immediately preceding the claim. Nothing in these terms excludes or limits liability that cannot be excluded or limited under the ACL.",
  UK: "To the maximum extent permitted by the Consumer Rights Act 2015 and applicable English law, Marco Reid's total aggregate liability for any claims shall not exceed the total fees paid by you in the twelve (12) months immediately preceding the claim. Nothing in these terms excludes or limits liability for death or personal injury caused by negligence, fraud, or any other liability that cannot be excluded or limited by law.",
  US: "TO THE MAXIMUM EXTENT PERMITTED BY APPLICABLE LAW, MARCO REID'S TOTAL AGGREGATE LIABILITY FOR ANY AND ALL CLAIMS ARISING FROM OR RELATING TO THESE TERMS OR YOUR USE OF THE PLATFORM SHALL NOT EXCEED THE TOTAL FEES PAID BY YOU IN THE TWELVE (12) MONTHS IMMEDIATELY PRECEDING THE FIRST EVENT GIVING RISE TO LIABILITY. THIS LIMITATION APPLIES REGARDLESS OF THE FORM OF ACTION, WHETHER IN CONTRACT, TORT, STRICT LIABILITY, OR OTHERWISE.",
  CA: "To the maximum extent permitted by applicable Canadian federal and provincial law, including the Competition Act and applicable provincial consumer protection legislation, Marco Reid's total aggregate liability shall not exceed the total fees paid by you in the twelve (12) months immediately preceding the claim.",
};

// Jurisdiction-specific governing law clauses
export const GOVERNING_LAW: Record<string, string> = {
  NZ: "These terms shall be governed by and construed in accordance with the laws of New Zealand. Any disputes shall be subject to the exclusive jurisdiction of the courts of New Zealand, sitting in Auckland.",
  AU: "These terms shall be governed by and construed in accordance with the laws of New South Wales, Australia. Any disputes shall be subject to the exclusive jurisdiction of the courts of New South Wales.",
  UK: "These terms shall be governed by and construed in accordance with the laws of England and Wales. Any disputes shall be subject to the exclusive jurisdiction of the courts of England and Wales.",
  US: "These terms shall be governed by and construed in accordance with the laws of the State of Delaware, without regard to its conflict of laws provisions. Any disputes shall be resolved through binding arbitration under the rules of the American Arbitration Association, conducted in English.",
  CA: "These terms shall be governed by and construed in accordance with the laws of the Province of Ontario and the federal laws of Canada applicable therein. For Quebec residents, these terms are governed by the laws of Quebec and the federal laws of Canada. Any disputes shall be subject to the exclusive jurisdiction of the courts of Ontario (or Quebec, for Quebec residents).",
};

// Professional responsibility notices per jurisdiction
export const PROFESSIONAL_RESPONSIBILITY: Record<string, string> = {
  NZ: "Licensed NZ lawyers remain subject to the Lawyers and Conveyancers Act 2006, the Lawyers and Conveyancers Act (Lawyers: Conduct and Client Care) Rules 2008, and the oversight of the New Zealand Law Society. Use of Marco Reid does not diminish, transfer, or modify your professional obligations. Licensed NZ accountants remain subject to the governance of CA ANZ and the Tax Administration Act 1994.",
  AU: "Licensed Australian legal practitioners remain subject to the Legal Profession Uniform Law (where applicable), state-based Legal Profession Acts, and the oversight of their state or territory Law Society or Legal Services Board. Use of Marco Reid does not diminish your professional obligations. Tax practitioners remain subject to the Tax Agent Services Act 2009 and oversight by the Tax Practitioners Board.",
  UK: "Solicitors remain subject to the SRA Standards and Regulations, the Solicitors Act 1974, and oversight by the Solicitors Regulation Authority. Barristers remain subject to the BSB Handbook and oversight by the Bar Standards Board. Use of Marco Reid does not diminish, transfer, or modify your professional obligations. Accountants remain subject to their professional body's ethical standards.",
  US: "Licensed attorneys remain subject to the Rules of Professional Conduct of their state(s) of licensure and the oversight of their state bar association(s). Use of Marco Reid does not diminish your duty of competence (Model Rule 1.1), duty of diligence (Model Rule 1.3), or duty of supervision over AI outputs (Model Rule 5.3). CPAs remain subject to the AICPA Code of Professional Conduct and their state board of accountancy.",
  CA: "Licensed lawyers and paralegals remain subject to the rules of their provincial Law Society, the Federation of Law Societies' Model Code of Professional Conduct, and applicable provincial legislation. Use of Marco Reid does not diminish your professional obligations. CPAs remain subject to CPA Canada's Code of Professional Conduct and their provincial CPA body.",
};
