export interface ProactiveAlert {
  id: string;
  type: "deadline-risk" | "visa-expiry" | "trust-balance" | "legislative-change" | "billing-opportunity" | "client-risk" | "compliance-gap" | "document-expiry";
  severity: "critical" | "warning" | "info" | "opportunity";
  title: string;
  description: string;
  action: string;
  actionUrl: string;
  matterId?: string;
  clientId?: string;
  dismissible: boolean;
  createdAt: string;
}

// Simulated proactive alerts engine
// In production, these would be generated by a background job scanning matters, deadlines, trust accounts, and regulatory feeds
export function generateProactiveAlerts(params: {
  userId: string;
  jurisdiction: string;
  activeMatters: number;
  upcomingDeadlines: number;
  trustBalance: number;
  overdueInvoices: number;
}): ProactiveAlert[] {
  const alerts: ProactiveAlert[] = [];
  const now = new Date().toISOString();

  // Deadline risk alerts
  if (params.upcomingDeadlines > 0) {
    alerts.push({
      id: "deadline-risk-1",
      type: "deadline-risk",
      severity: "critical",
      title: "Filing deadline in 3 days",
      description: "Rodriguez H-1B petition (I-129) must be filed by Friday. Receipt notice not yet uploaded.",
      action: "Review matter",
      actionUrl: "/deadlines",
      dismissible: false,
      createdAt: now,
    });
  }

  // Trust balance warning
  if (params.trustBalance < 50000) {
    alerts.push({
      id: "trust-low-1",
      type: "trust-balance",
      severity: "warning",
      title: "Client trust balance running low",
      description: "Thornton trust account balance is $342.50. Estimated fees for next billing cycle exceed current balance. Request replenishment now to avoid fee draw rejection.",
      action: "View trust account",
      actionUrl: "/trust",
      dismissible: true,
      createdAt: now,
    });
  }

  // Legislative change impact
  alerts.push({
    id: "legislative-1",
    type: "legislative-change",
    severity: "info",
    title: "New regulation may affect 3 active matters",
    description: `${params.jurisdiction === "NZ" ? "IR has updated provisional tax rules effective next month" : params.jurisdiction === "UK" ? "HMRC MTD quarterly reporting threshold reduced" : "IRS released new guidance on Section 174 R&D amortization"}. Review affected matters for compliance impact.`,
    action: "View regulatory alerts",
    actionUrl: "/alerts",
    dismissible: true,
    createdAt: now,
  });

  // Billing opportunity
  if (params.activeMatters > 3) {
    alerts.push({
      id: "billing-opp-1",
      type: "billing-opportunity",
      severity: "opportunity",
      title: "Unbilled time detected — $4,200 recoverable",
      description: "You have 12 hours of unbilled time across 4 matters this month. Industry average collection rate is 94%. Generate invoices now to maintain cash flow.",
      action: "Generate invoices",
      actionUrl: "/billing/invoices/new",
      dismissible: true,
      createdAt: now,
    });
  }

  // Visa expiry (immigration)
  alerts.push({
    id: "visa-expiry-1",
    type: "visa-expiry",
    severity: "warning",
    title: "Client visa expiring in 87 days",
    description: "Chen, Wei — Skilled Worker visa expires 11 August 2026. No extension application filed. Processing times suggest filing within 30 days to avoid gap.",
    action: "View matter",
    actionUrl: "/matters",
    dismissible: false,
    createdAt: now,
  });

  // Client risk
  if (params.overdueInvoices > 0) {
    alerts.push({
      id: "client-risk-1",
      type: "client-risk",
      severity: "warning",
      title: "Client payment behaviour deteriorating",
      description: "Meridian Corp has 2 invoices overdue (45+ days). Historical pattern shows clients with 2+ overdue invoices have 60% probability of becoming bad debt. Consider pausing work or requesting retainer.",
      action: "View client",
      actionUrl: "/clients",
      dismissible: true,
      createdAt: now,
    });
  }

  // Compliance gap
  alerts.push({
    id: "compliance-1",
    type: "compliance-gap",
    severity: "warning",
    title: "AML verification overdue for 2 clients",
    description: "KYC verification for Thompson, R. and Pacific Holdings Ltd has not been completed. Your jurisdiction requires client verification before acting. Complete verification to remain compliant.",
    action: "Complete verification",
    actionUrl: "/clients",
    dismissible: false,
    createdAt: now,
  });

  return alerts;
}
