export interface Service {
  slug: string;
  name: string;
  category: "legal" | "accounting" | "immigration" | "property" | "business" | "personal" | "tax" | "court";
  description: string;
  publicAccess: boolean; // Can the public self-serve this?
  professionalRequired: boolean; // Does this REQUIRE a licensed professional?
  countries: string[]; // Which countries offer this service
  forms?: string[]; // Related forms/documents
  estimatedCost?: string; // Rough guide
}

export const SERVICES: Service[] = [
  // === PERSONAL / WILLS & ESTATES ===
  { slug: "wills", name: "Wills & Testaments", category: "personal", description: "Draft, review, and register your last will and testament.", publicAccess: true, professionalRequired: false, countries: ["NZ", "AU", "UK", "US", "CA", "IE", "SG"], forms: ["Simple Will", "Mirror Wills", "Testamentary Trust Will"] },
  { slug: "enduring-power-of-attorney", name: "Enduring Power of Attorney", category: "personal", description: "Appoint someone to make decisions on your behalf if you lose capacity.", publicAccess: true, professionalRequired: false, countries: ["NZ", "AU", "UK", "US", "CA", "IE", "SG"], forms: ["EPA — Property", "EPA — Personal Care & Welfare", "LPA — Health & Welfare (UK)", "Durable POA (US)"] },
  { slug: "probate", name: "Probate & Estate Administration", category: "personal", description: "Apply for probate and administer a deceased person's estate.", publicAccess: false, professionalRequired: true, countries: ["NZ", "AU", "UK", "US", "CA", "IE", "SG"] },
  { slug: "family-trusts", name: "Family Trusts", category: "personal", description: "Establish and manage family trusts for asset protection and estate planning.", publicAccess: false, professionalRequired: true, countries: ["NZ", "AU", "UK", "US", "CA", "IE", "SG"] },

  // === PROPERTY / CONVEYANCING ===
  { slug: "conveyancing", name: "Conveyancing (Property Transfer)", category: "property", description: "Buy, sell, or transfer property with full legal support.", publicAccess: false, professionalRequired: true, countries: ["NZ", "AU", "UK", "IE"], forms: ["Sale & Purchase Agreement", "Title Search", "LIM Report (NZ)", "Section 32 (AU)"] },
  { slug: "residential-tenancy", name: "Residential Tenancy Agreements", category: "property", description: "Create and manage residential rental agreements.", publicAccess: true, professionalRequired: false, countries: ["NZ", "AU", "UK", "US", "CA", "IE", "SG"], forms: ["Residential Tenancy Agreement", "Bond Lodgement", "Lease Agreement"] },
  { slug: "commercial-lease", name: "Commercial Leases", category: "property", description: "Draft, review, and negotiate commercial lease agreements.", publicAccess: false, professionalRequired: true, countries: ["NZ", "AU", "UK", "US", "CA", "IE", "SG"] },
  { slug: "property-disputes", name: "Property Disputes", category: "property", description: "Resolve boundary disputes, easements, and property-related conflicts.", publicAccess: false, professionalRequired: true, countries: ["NZ", "AU", "UK", "US", "CA", "IE"] },

  // === BUSINESS / CORPORATE ===
  { slug: "company-formation", name: "Company Formation & Incorporation", category: "business", description: "Register a new company, set up directors, and issue shares.", publicAccess: true, professionalRequired: false, countries: ["NZ", "AU", "UK", "US", "CA", "IE", "SG"], forms: ["Company Registration", "Constitution/Articles", "Shareholder Agreement", "Director Consent"], estimatedCost: "From $199" },
  { slug: "partnership-agreements", name: "Partnership Agreements", category: "business", description: "Draft and formalise partnership agreements for business ventures.", publicAccess: true, professionalRequired: false, countries: ["NZ", "AU", "UK", "US", "CA", "IE", "SG"] },
  { slug: "shareholder-agreements", name: "Shareholder Agreements", category: "business", description: "Protect shareholder rights and define governance structures.", publicAccess: false, professionalRequired: true, countries: ["NZ", "AU", "UK", "US", "CA", "IE", "SG"] },
  { slug: "terms-and-conditions", name: "Website Terms & Conditions", category: "business", description: "Generate legally compliant terms of service for your website or app.", publicAccess: true, professionalRequired: false, countries: ["NZ", "AU", "UK", "US", "CA", "IE", "SG"] },
  { slug: "privacy-policy-generator", name: "Privacy Policy Generator", category: "business", description: "Create a privacy policy compliant with your jurisdiction's data protection laws.", publicAccess: true, professionalRequired: false, countries: ["NZ", "AU", "UK", "US", "CA", "IE", "SG"] },
  { slug: "employment-agreements", name: "Employment Agreements", category: "business", description: "Draft compliant employment contracts for your staff.", publicAccess: true, professionalRequired: false, countries: ["NZ", "AU", "UK", "US", "CA", "IE", "SG"], forms: ["Individual Employment Agreement", "Fixed-Term Contract", "Independent Contractor Agreement"] },
  { slug: "business-sale", name: "Business Sale & Purchase", category: "business", description: "Buy or sell a business with full legal and accounting support.", publicAccess: false, professionalRequired: true, countries: ["NZ", "AU", "UK", "US", "CA", "IE", "SG"] },
  { slug: "trademark-registration", name: "Trademark Registration", category: "business", description: "Register and protect your brand name, logo, or slogan.", publicAccess: true, professionalRequired: false, countries: ["NZ", "AU", "UK", "US", "CA", "IE", "SG"], forms: ["Trademark Application", "Opposition Response"], estimatedCost: "From $499" },

  // === IMMIGRATION ===
  { slug: "work-visas", name: "Work Visas & Permits", category: "immigration", description: "Apply for employer-sponsored and independent work visas.", publicAccess: false, professionalRequired: true, countries: ["NZ", "AU", "UK", "US", "CA", "IE", "SG"] },
  { slug: "residence-visas", name: "Residence & Permanent Residency", category: "immigration", description: "Apply for permanent residence through skilled, family, or investor pathways.", publicAccess: false, professionalRequired: true, countries: ["NZ", "AU", "UK", "US", "CA", "IE", "SG"] },
  { slug: "student-visas", name: "Student Visas", category: "immigration", description: "Apply for study permits and student visas.", publicAccess: true, professionalRequired: false, countries: ["NZ", "AU", "UK", "US", "CA", "IE", "SG"] },
  { slug: "partner-visas", name: "Partner & Family Visas", category: "immigration", description: "Sponsor your partner or family member for a visa.", publicAccess: false, professionalRequired: true, countries: ["NZ", "AU", "UK", "US", "CA", "IE", "SG"] },
  { slug: "citizenship", name: "Citizenship Applications", category: "immigration", description: "Apply for citizenship by naturalisation or descent.", publicAccess: true, professionalRequired: false, countries: ["NZ", "AU", "UK", "US", "CA", "IE"] },

  // === TAX & ACCOUNTING ===
  { slug: "individual-tax-returns", name: "Individual Tax Returns", category: "tax", description: "File your annual individual income tax return.", publicAccess: true, professionalRequired: false, countries: ["NZ", "AU", "UK", "US", "CA", "IE", "SG"], forms: ["IR3 (NZ)", "Individual Return (AU)", "SA100 (UK)", "1040 (US)", "T1 (CA)", "Form 11 (IE)"] },
  { slug: "company-tax-returns", name: "Company Tax Returns", category: "tax", description: "File annual corporate income tax returns.", publicAccess: false, professionalRequired: true, countries: ["NZ", "AU", "UK", "US", "CA", "IE", "SG"], forms: ["IR4 (NZ)", "Company Return (AU)", "CT600 (UK)", "1120 (US)", "T2 (CA)", "CT1 (IE)"] },
  { slug: "gst-vat-returns", name: "GST / VAT Returns", category: "tax", description: "File goods and services tax or value-added tax returns.", publicAccess: true, professionalRequired: false, countries: ["NZ", "AU", "UK", "CA", "IE", "SG"], forms: ["GST101A (NZ)", "BAS (AU)", "VAT Return (UK)", "GST/HST (CA)", "VAT3 (IE)", "GST F5 (SG)"] },
  { slug: "payroll-services", name: "Payroll Services", category: "accounting", description: "Run payroll, calculate tax, and file employer returns.", publicAccess: false, professionalRequired: true, countries: ["NZ", "AU", "UK", "US", "CA", "IE", "SG"] },
  { slug: "bookkeeping", name: "Bookkeeping", category: "accounting", description: "Ongoing bookkeeping and financial record management.", publicAccess: false, professionalRequired: false, countries: ["NZ", "AU", "UK", "US", "CA", "IE", "SG"] },
  { slug: "financial-statements", name: "Financial Statements", category: "accounting", description: "Prepare annual financial statements and accounts.", publicAccess: false, professionalRequired: true, countries: ["NZ", "AU", "UK", "US", "CA", "IE", "SG"] },
  { slug: "tax-planning", name: "Tax Planning & Advisory", category: "tax", description: "Strategic tax planning to minimise your tax obligations legally.", publicAccess: false, professionalRequired: true, countries: ["NZ", "AU", "UK", "US", "CA", "IE", "SG"] },
  { slug: "catch-up-filing", name: "Catch-Up Filing (Overdue Returns)", category: "tax", description: "Get years of overdue tax returns filed and back on track.", publicAccess: true, professionalRequired: true, countries: ["NZ", "AU", "UK", "US", "CA", "IE"], estimatedCost: "From $499/year" },

  // === LEGAL / DISPUTES ===
  { slug: "contract-drafting", name: "Contract Drafting & Review", category: "legal", description: "Draft, review, or negotiate any type of commercial contract.", publicAccess: false, professionalRequired: true, countries: ["NZ", "AU", "UK", "US", "CA", "IE", "SG"] },
  { slug: "debt-recovery", name: "Debt Recovery", category: "legal", description: "Recover unpaid debts through demand letters, mediation, or litigation.", publicAccess: true, professionalRequired: false, countries: ["NZ", "AU", "UK", "US", "CA", "IE", "SG"], forms: ["Letter of Demand", "Statutory Demand"] },
  { slug: "dispute-resolution", name: "Dispute Resolution & Mediation", category: "legal", description: "Resolve disputes through mediation, arbitration, or negotiation.", publicAccess: false, professionalRequired: true, countries: ["NZ", "AU", "UK", "US", "CA", "IE", "SG"] },
  { slug: "employment-disputes", name: "Employment Disputes", category: "legal", description: "Resolve workplace grievances, unfair dismissal, and employment claims.", publicAccess: true, professionalRequired: false, countries: ["NZ", "AU", "UK", "US", "CA", "IE", "SG"] },
  { slug: "family-law", name: "Family Law (Divorce & Separation)", category: "legal", description: "Legal support for divorce, separation, custody, and relationship property.", publicAccess: false, professionalRequired: true, countries: ["NZ", "AU", "UK", "US", "CA", "IE"] },
  { slug: "criminal-defence", name: "Criminal Defence", category: "legal", description: "Legal representation for criminal charges and proceedings.", publicAccess: false, professionalRequired: true, countries: ["NZ", "AU", "UK", "US", "CA", "IE", "SG"] },
  { slug: "personal-injury", name: "Personal Injury Claims", category: "legal", description: "Claim compensation for injuries caused by negligence.", publicAccess: true, professionalRequired: true, countries: ["AU", "UK", "US", "CA", "IE"] },
  { slug: "insolvency", name: "Insolvency & Liquidation", category: "legal", description: "Navigate business insolvency, liquidation, or personal bankruptcy.", publicAccess: false, professionalRequired: true, countries: ["NZ", "AU", "UK", "US", "CA", "IE", "SG"] },

  // === COURT ===
  { slug: "court-filing", name: "Court Filing & E-Filing", category: "court", description: "File documents with courts electronically.", publicAccess: false, professionalRequired: true, countries: ["NZ", "AU", "UK", "US", "CA", "SG"] },
  { slug: "notarisation", name: "Notarisation & Certification", category: "court", description: "Get documents notarised or certified for legal use.", publicAccess: true, professionalRequired: true, countries: ["NZ", "AU", "UK", "US", "CA", "IE", "SG"] },
  { slug: "apostille", name: "Apostille & Legalisation", category: "court", description: "Get documents authenticated for use in foreign countries.", publicAccess: true, professionalRequired: false, countries: ["NZ", "AU", "UK", "US", "CA", "IE", "SG"] },

  // =============================================
  // === PROPERTY & REAL ESTATE (additional) ===
  // =============================================
  { slug: "mortgage-refinancing-documentation", name: "Mortgage & Refinancing Documentation", category: "property", description: "Prepare and review mortgage documents, refinancing agreements, and loan security instruments.", publicAccess: false, professionalRequired: true, countries: ["NZ", "AU", "UK", "US", "CA", "IE", "SG", "IN"] },
  { slug: "property-title-disputes", name: "Property Title Disputes", category: "property", description: "Resolve disputes over property ownership, title defects, and registration errors.", publicAccess: false, professionalRequired: true, countries: ["NZ", "AU", "UK", "US", "CA", "IE", "SG", "IN"] },
  { slug: "easement-right-of-way", name: "Easement & Right of Way", category: "property", description: "Establish, modify, or dispute easements and rights of way over land.", publicAccess: false, professionalRequired: true, countries: ["NZ", "AU", "UK", "US", "CA", "IE", "SG", "IN"] },
  { slug: "subdivision-resource-consent", name: "Subdivision & Resource Consent", category: "property", description: "Navigate the legal requirements for subdividing land and obtaining resource consents or planning permissions.", publicAccess: false, professionalRequired: true, countries: ["NZ", "AU", "UK", "US", "CA", "IE", "IN"] },
  { slug: "body-corporate-strata-hoa-disputes", name: "Body Corporate / Strata / HOA Disputes", category: "property", description: "Resolve disputes involving body corporates, strata committees, or homeowners' associations.", publicAccess: false, professionalRequired: true, countries: ["NZ", "AU", "UK", "US", "CA", "IE", "SG", "IN"] },
  { slug: "adverse-possession", name: "Adverse Possession Claims", category: "property", description: "Claim or defend against adverse possession (squatter's rights) applications over land.", publicAccess: false, professionalRequired: true, countries: ["NZ", "AU", "UK", "US", "CA", "IE", "IN"] },
  { slug: "construction-law-defects", name: "Construction Law & Defects", category: "property", description: "Legal advice on building defects, construction contracts, and disputes with builders or developers.", publicAccess: false, professionalRequired: true, countries: ["NZ", "AU", "UK", "US", "CA", "IE", "SG", "IN"] },

  // =============================================
  // === FAMILY LAW (additional) ===
  // =============================================
  { slug: "prenuptial-relationship-property", name: "Prenuptial / Relationship Property Agreements", category: "personal", description: "Draft contracting-out or prenuptial agreements to define property rights before or during a relationship.", publicAccess: false, professionalRequired: true, countries: ["NZ", "AU", "UK", "US", "CA", "IE", "SG", "IN"] },
  { slug: "child-custody-guardianship", name: "Child Custody & Guardianship", category: "personal", description: "Apply for custody, guardianship, or parenting orders for children.", publicAccess: false, professionalRequired: true, countries: ["NZ", "AU", "UK", "US", "CA", "IE", "SG", "IN"] },
  { slug: "adoption", name: "Adoption", category: "personal", description: "Legal support for domestic and international adoption applications.", publicAccess: false, professionalRequired: true, countries: ["NZ", "AU", "UK", "US", "CA", "IE", "SG", "IN"] },
  { slug: "domestic-violence-protection-orders", name: "Domestic Violence Protection Orders", category: "personal", description: "Apply for or defend against protection orders, restraining orders, and non-molestation orders.", publicAccess: true, professionalRequired: false, countries: ["NZ", "AU", "UK", "US", "CA", "IE", "SG", "IN"] },
  { slug: "child-support-disputes", name: "Child Support Disputes", category: "personal", description: "Resolve disputes over child support payments, assessments, and arrears.", publicAccess: false, professionalRequired: true, countries: ["NZ", "AU", "UK", "US", "CA", "IE", "IN"] },
  { slug: "paternity-parentage", name: "Paternity / Parentage", category: "personal", description: "Establish or challenge legal parentage through DNA testing and court declarations.", publicAccess: false, professionalRequired: true, countries: ["NZ", "AU", "UK", "US", "CA", "IE", "SG", "IN"] },

  // =============================================
  // === CRIMINAL LAW (additional) ===
  // =============================================
  { slug: "dui-drink-driving-defence", name: "DUI / Drink Driving Defence", category: "legal", description: "Defence representation for driving under the influence or excess breath/blood alcohol charges.", publicAccess: false, professionalRequired: true, countries: ["NZ", "AU", "UK", "US", "CA", "IE", "SG", "IN"] },
  { slug: "drug-offences", name: "Drug Offences", category: "legal", description: "Defence for drug possession, supply, manufacturing, and importation charges.", publicAccess: false, professionalRequired: true, countries: ["NZ", "AU", "UK", "US", "CA", "IE", "SG", "IN"] },
  { slug: "fraud-white-collar-crime", name: "Fraud & White Collar Crime", category: "legal", description: "Defence and advisory for fraud, embezzlement, bribery, and financial crime charges.", publicAccess: false, professionalRequired: true, countries: ["NZ", "AU", "UK", "US", "CA", "IE", "SG", "IN"] },
  { slug: "assault-violent-offences", name: "Assault & Violent Offences", category: "legal", description: "Defence representation for assault, wounding, and violent criminal charges.", publicAccess: false, professionalRequired: true, countries: ["NZ", "AU", "UK", "US", "CA", "IE", "SG", "IN"] },
  { slug: "theft-burglary", name: "Theft & Burglary", category: "legal", description: "Defence for theft, burglary, robbery, and dishonesty offences.", publicAccess: false, professionalRequired: true, countries: ["NZ", "AU", "UK", "US", "CA", "IE", "SG", "IN"] },
  { slug: "sexual-offences-defence", name: "Sexual Offences Defence", category: "legal", description: "Specialist defence representation for sexual offence allegations and charges.", publicAccess: false, professionalRequired: true, countries: ["NZ", "AU", "UK", "US", "CA", "IE", "SG", "IN"] },
  { slug: "traffic-offences", name: "Traffic Offences", category: "legal", description: "Defence for speeding, dangerous driving, driving while disqualified, and other traffic violations.", publicAccess: false, professionalRequired: true, countries: ["NZ", "AU", "UK", "US", "CA", "IE", "SG", "IN"] },
  { slug: "appeals-sentence-review", name: "Appeals & Sentence Review", category: "legal", description: "Appeal a conviction or sentence, or apply for a sentence review.", publicAccess: false, professionalRequired: true, countries: ["NZ", "AU", "UK", "US", "CA", "IE", "SG", "IN"] },
  { slug: "youth-juvenile-court", name: "Youth / Juvenile Court", category: "legal", description: "Specialist representation for young people facing criminal charges in youth or family courts.", publicAccess: false, professionalRequired: true, countries: ["NZ", "AU", "UK", "US", "CA", "IE", "SG", "IN"] },

  // =============================================
  // === CIVIL LITIGATION (additional) ===
  // =============================================
  { slug: "class-action-group-litigation", name: "Class Action / Group Litigation", category: "legal", description: "Represent or join class actions and group litigation claims against corporations or government.", publicAccess: false, professionalRequired: true, countries: ["NZ", "AU", "UK", "US", "CA", "IE", "SG", "IN"] },
  { slug: "defamation-claims", name: "Defamation Claims", category: "legal", description: "Pursue or defend defamation, libel, and slander claims.", publicAccess: false, professionalRequired: true, countries: ["NZ", "AU", "UK", "US", "CA", "IE", "SG", "IN"] },
  { slug: "negligence-claims", name: "Negligence Claims", category: "legal", description: "Claim compensation for loss or injury caused by another party's negligence.", publicAccess: false, professionalRequired: true, countries: ["NZ", "AU", "UK", "US", "CA", "IE", "SG", "IN"] },
  { slug: "insurance-disputes", name: "Insurance Disputes", category: "legal", description: "Dispute denied or underpaid insurance claims and policy interpretation issues.", publicAccess: false, professionalRequired: true, countries: ["NZ", "AU", "UK", "US", "CA", "IE", "SG", "IN"] },
  { slug: "medical-malpractice", name: "Medical Malpractice", category: "legal", description: "Claim compensation for injury or harm caused by medical negligence.", publicAccess: false, professionalRequired: true, countries: ["AU", "UK", "US", "CA", "IE", "SG", "IN"] },
  { slug: "consumer-protection-claims", name: "Consumer Protection Claims", category: "legal", description: "Pursue claims under consumer guarantees, fair trading, and product liability laws.", publicAccess: true, professionalRequired: false, countries: ["NZ", "AU", "UK", "US", "CA", "IE", "SG", "IN"] },
  { slug: "neighbour-disputes", name: "Neighbour Disputes", category: "legal", description: "Resolve disputes involving fences, trees, noise, boundaries, and nuisance between neighbours.", publicAccess: true, professionalRequired: false, countries: ["NZ", "AU", "UK", "US", "CA", "IE", "SG", "IN"] },
  { slug: "judicial-review", name: "Judicial Review", category: "legal", description: "Challenge government or public body decisions through judicial review proceedings.", publicAccess: false, professionalRequired: true, countries: ["NZ", "AU", "UK", "US", "CA", "IE", "SG", "IN"] },

  // =============================================
  // === CORPORATE / COMMERCIAL (additional) ===
  // =============================================
  { slug: "mergers-acquisitions", name: "Mergers & Acquisitions", category: "business", description: "Legal and financial advisory for buying, selling, or merging companies.", publicAccess: false, professionalRequired: true, countries: ["NZ", "AU", "UK", "US", "CA", "IE", "SG", "IN"] },
  { slug: "joint-ventures", name: "Joint Ventures", category: "business", description: "Structure and document joint venture arrangements between two or more parties.", publicAccess: false, professionalRequired: true, countries: ["NZ", "AU", "UK", "US", "CA", "IE", "SG", "IN"] },
  { slug: "franchise-agreements", name: "Franchise Agreements", category: "business", description: "Draft, review, and negotiate franchise agreements and disclosure documents.", publicAccess: false, professionalRequired: true, countries: ["NZ", "AU", "UK", "US", "CA", "IE", "SG", "IN"] },
  { slug: "distribution-agreements", name: "Distribution Agreements", category: "business", description: "Create agreements for product distribution, agency, and reseller arrangements.", publicAccess: false, professionalRequired: true, countries: ["NZ", "AU", "UK", "US", "CA", "IE", "SG", "IN"] },
  { slug: "non-disclosure-agreements", name: "Non-Disclosure Agreements (NDA)", category: "business", description: "Protect confidential information with legally binding NDAs.", publicAccess: true, professionalRequired: false, countries: ["NZ", "AU", "UK", "US", "CA", "IE", "SG", "IN"], forms: ["Mutual NDA", "One-Way NDA"] },
  { slug: "non-compete-agreements", name: "Non-Compete Agreements", category: "business", description: "Draft and enforce non-compete and restraint of trade clauses.", publicAccess: false, professionalRequired: true, countries: ["NZ", "AU", "UK", "US", "CA", "IE", "SG", "IN"] },
  { slug: "licensing-agreements", name: "Licensing Agreements", category: "business", description: "License intellectual property, software, or technology through formal agreements.", publicAccess: false, professionalRequired: true, countries: ["NZ", "AU", "UK", "US", "CA", "IE", "SG", "IN"] },
  { slug: "supply-agreements", name: "Supply Agreements", category: "business", description: "Draft and negotiate supply contracts for goods and raw materials.", publicAccess: false, professionalRequired: true, countries: ["NZ", "AU", "UK", "US", "CA", "IE", "SG", "IN"] },
  { slug: "terms-of-trade", name: "Terms of Trade", category: "business", description: "Create standard terms of trade governing commercial transactions with customers and suppliers.", publicAccess: true, professionalRequired: false, countries: ["NZ", "AU", "UK", "US", "CA", "IE", "SG", "IN"] },
  { slug: "service-level-agreements", name: "Service Level Agreements", category: "business", description: "Define service standards, KPIs, and remedies in formal SLA documents.", publicAccess: true, professionalRequired: false, countries: ["NZ", "AU", "UK", "US", "CA", "IE", "SG", "IN"] },
  { slug: "shareholders-disputes", name: "Shareholders' Disputes", category: "business", description: "Resolve disputes between shareholders including oppression claims and deadlocks.", publicAccess: false, professionalRequired: true, countries: ["NZ", "AU", "UK", "US", "CA", "IE", "SG", "IN"] },
  { slug: "director-duties-liability", name: "Director Duties & Liability", category: "business", description: "Advise directors on their statutory duties, potential liabilities, and personal exposure.", publicAccess: false, professionalRequired: true, countries: ["NZ", "AU", "UK", "US", "CA", "IE", "SG", "IN"] },
  { slug: "company-reconstruction", name: "Company Reconstruction", category: "business", description: "Restructure distressed companies through voluntary administration, schemes of arrangement, or receivership.", publicAccess: false, professionalRequired: true, countries: ["NZ", "AU", "UK", "US", "CA", "IE", "SG", "IN"] },
  { slug: "due-diligence-legal", name: "Due Diligence (Legal)", category: "business", description: "Conduct comprehensive legal due diligence on target companies, assets, or transactions.", publicAccess: false, professionalRequired: true, countries: ["NZ", "AU", "UK", "US", "CA", "IE", "SG", "IN"] },

  // =============================================
  // === EMPLOYMENT LAW (additional) ===
  // =============================================
  { slug: "wrongful-unfair-dismissal", name: "Wrongful Dismissal / Unfair Dismissal", category: "legal", description: "Challenge an unfair or wrongful termination of employment through legal proceedings.", publicAccess: true, professionalRequired: true, countries: ["NZ", "AU", "UK", "US", "CA", "IE", "SG", "IN"] },
  { slug: "redundancy-advice", name: "Redundancy Advice", category: "legal", description: "Legal advice on redundancy processes, entitlements, and challenging genuine redundancy.", publicAccess: true, professionalRequired: false, countries: ["NZ", "AU", "UK", "US", "CA", "IE", "SG", "IN"] },
  { slug: "workplace-harassment-bullying", name: "Workplace Harassment & Bullying", category: "legal", description: "Address workplace bullying, harassment, and discrimination through legal channels.", publicAccess: true, professionalRequired: false, countries: ["NZ", "AU", "UK", "US", "CA", "IE", "SG", "IN"] },
  { slug: "employment-mediation", name: "Employment Mediation", category: "legal", description: "Resolve employment disputes through formal mediation services.", publicAccess: true, professionalRequired: false, countries: ["NZ", "AU", "UK", "US", "CA", "IE", "SG", "IN"] },
  { slug: "restrictive-covenants", name: "Restrictive Covenants", category: "legal", description: "Draft, enforce, or challenge restrictive covenants in employment contracts.", publicAccess: false, professionalRequired: true, countries: ["NZ", "AU", "UK", "US", "CA", "IE", "SG", "IN"] },
  { slug: "workplace-health-safety", name: "Workplace Health & Safety", category: "legal", description: "Legal advice on workplace health and safety obligations, incidents, and prosecutions.", publicAccess: false, professionalRequired: true, countries: ["NZ", "AU", "UK", "US", "CA", "IE", "SG", "IN"] },

  // =============================================
  // === IMMIGRATION (additional) ===
  // =============================================
  { slug: "deportation-removal-defence", name: "Deportation & Removal Defence", category: "immigration", description: "Defend against deportation, removal, or exclusion orders.", publicAccess: false, professionalRequired: true, countries: ["NZ", "AU", "UK", "US", "CA", "IE", "SG", "IN"] },
  { slug: "refugee-asylum-claims", name: "Refugee & Asylum Claims", category: "immigration", description: "Apply for refugee status or asylum protection and navigate the claims process.", publicAccess: false, professionalRequired: true, countries: ["NZ", "AU", "UK", "US", "CA", "IE", "IN"] },
  { slug: "immigration-appeals", name: "Immigration Appeals", category: "immigration", description: "Appeal visa refusals, deportation decisions, and other immigration outcomes.", publicAccess: false, professionalRequired: true, countries: ["NZ", "AU", "UK", "US", "CA", "IE", "SG", "IN"] },
  { slug: "character-waiver-applications", name: "Character Waiver Applications", category: "immigration", description: "Apply for character waivers where criminal convictions or character concerns affect visa eligibility.", publicAccess: false, professionalRequired: true, countries: ["NZ", "AU", "UK", "US", "CA", "IE"] },
  { slug: "employer-accreditation", name: "Employer Accreditation (NZ)", category: "immigration", description: "Obtain employer accreditation to sponsor migrant workers under the AEWV scheme.", publicAccess: false, professionalRequired: true, countries: ["NZ"] },
  { slug: "sponsor-licence", name: "Sponsor Licence (UK)", category: "immigration", description: "Apply for a UK sponsor licence to hire overseas workers.", publicAccess: false, professionalRequired: true, countries: ["UK"] },

  // =============================================
  // === INTELLECTUAL PROPERTY (additional) ===
  // =============================================
  { slug: "patent-applications", name: "Patent Applications & Prosecution", category: "legal", description: "File patent applications and manage prosecution through to grant.", publicAccess: false, professionalRequired: true, countries: ["NZ", "AU", "UK", "US", "CA", "IE", "SG", "IN"] },
  { slug: "copyright-registration-disputes", name: "Copyright Registration & Disputes", category: "legal", description: "Register copyrights and enforce or defend against copyright infringement claims.", publicAccess: true, professionalRequired: false, countries: ["NZ", "AU", "UK", "US", "CA", "IE", "SG", "IN"] },
  { slug: "domain-name-disputes", name: "Domain Name Disputes", category: "legal", description: "Resolve domain name disputes through UDRP proceedings or court action.", publicAccess: false, professionalRequired: true, countries: ["NZ", "AU", "UK", "US", "CA", "IE", "SG", "IN"] },
  { slug: "trade-secret-protection", name: "Trade Secret Protection", category: "legal", description: "Protect trade secrets and pursue remedies for misappropriation of confidential business information.", publicAccess: false, professionalRequired: true, countries: ["NZ", "AU", "UK", "US", "CA", "IE", "SG", "IN"] },
  { slug: "ip-licensing-commercialisation", name: "IP Licensing & Commercialisation", category: "legal", description: "License, commercialise, and monetise intellectual property assets.", publicAccess: false, professionalRequired: true, countries: ["NZ", "AU", "UK", "US", "CA", "IE", "SG", "IN"] },
  { slug: "ip-due-diligence", name: "IP Due Diligence", category: "legal", description: "Assess intellectual property portfolios as part of transactions, investments, or acquisitions.", publicAccess: false, professionalRequired: true, countries: ["NZ", "AU", "UK", "US", "CA", "IE", "SG", "IN"] },

  // =============================================
  // === OTHER LEGAL SERVICES ===
  // =============================================
  { slug: "notarial-services", name: "Notarial Services", category: "legal", description: "Notarial acts including authenticating documents for international use.", publicAccess: false, professionalRequired: true, countries: ["NZ", "AU", "UK", "US", "CA", "IE", "SG", "IN"] },
  { slug: "affidavits-statutory-declarations", name: "Affidavits & Statutory Declarations", category: "legal", description: "Prepare and witness affidavits and statutory declarations for legal proceedings.", publicAccess: true, professionalRequired: false, countries: ["NZ", "AU", "UK", "US", "CA", "IE", "SG", "IN"], forms: ["Affidavit", "Statutory Declaration"] },
  { slug: "name-changes", name: "Name Changes", category: "personal", description: "Legally change your name through deed poll or court order.", publicAccess: true, professionalRequired: false, countries: ["NZ", "AU", "UK", "US", "CA", "IE", "SG", "IN"], forms: ["Deed Poll", "Name Change Application"] },
  { slug: "gender-marker-changes", name: "Gender Marker Changes", category: "personal", description: "Update your gender marker on official identification documents and birth certificates.", publicAccess: true, professionalRequired: false, countries: ["NZ", "AU", "UK", "US", "CA", "IE"] },
  { slug: "general-power-of-attorney", name: "Power of Attorney (General)", category: "personal", description: "Grant someone authority to act on your behalf for specific or general matters.", publicAccess: true, professionalRequired: false, countries: ["NZ", "AU", "UK", "US", "CA", "IE", "SG", "IN"], forms: ["General Power of Attorney", "Special Power of Attorney"] },
  { slug: "advance-care-directives", name: "Advance Care Directives / Living Wills", category: "personal", description: "Document your wishes for medical treatment if you become unable to communicate.", publicAccess: true, professionalRequired: false, countries: ["NZ", "AU", "UK", "US", "CA", "IE", "SG", "IN"], forms: ["Advance Directive", "Living Will", "Do Not Resuscitate"] },
  { slug: "privacy-data-breach-legal", name: "Privacy & Data Breach Legal Advice", category: "legal", description: "Legal advice on privacy compliance, data breaches, and notification obligations.", publicAccess: false, professionalRequired: true, countries: ["NZ", "AU", "UK", "US", "CA", "IE", "SG", "IN"] },
  { slug: "charity-nonprofit-formation", name: "Charity & Non-Profit Formation", category: "business", description: "Establish charities, non-profits, and incorporated societies with proper governance.", publicAccess: true, professionalRequired: false, countries: ["NZ", "AU", "UK", "US", "CA", "IE", "SG", "IN"] },
  { slug: "sports-law", name: "Sports Law", category: "legal", description: "Legal advice on athlete contracts, anti-doping, disciplinary proceedings, and sports governance.", publicAccess: false, professionalRequired: true, countries: ["NZ", "AU", "UK", "US", "CA", "IE", "SG", "IN"] },
  { slug: "entertainment-media-law", name: "Entertainment & Media Law", category: "legal", description: "Legal support for entertainment industry contracts, rights management, and content disputes.", publicAccess: false, professionalRequired: true, countries: ["NZ", "AU", "UK", "US", "CA", "IE", "SG", "IN"] },
  { slug: "maritime-admiralty-law", name: "Maritime / Admiralty Law", category: "legal", description: "Legal services for shipping, maritime accidents, cargo disputes, and admiralty claims.", publicAccess: false, professionalRequired: true, countries: ["NZ", "AU", "UK", "US", "CA", "IE", "SG", "IN"] },
  { slug: "aviation-law", name: "Aviation Law", category: "legal", description: "Legal advice on aviation regulations, aircraft transactions, and airline disputes.", publicAccess: false, professionalRequired: true, countries: ["NZ", "AU", "UK", "US", "CA", "IE", "SG", "IN"] },
  { slug: "mining-resources-law", name: "Mining & Resources Law", category: "legal", description: "Legal support for mining permits, resource extraction rights, and environmental compliance.", publicAccess: false, professionalRequired: true, countries: ["NZ", "AU", "UK", "US", "CA", "IE", "IN"] },
  { slug: "education-law", name: "Education Law", category: "legal", description: "Legal advice on student rights, school governance, exclusions, and education disputes.", publicAccess: false, professionalRequired: true, countries: ["NZ", "AU", "UK", "US", "CA", "IE", "SG", "IN"] },
  { slug: "health-law-medical-ethics", name: "Health Law & Medical Ethics", category: "legal", description: "Legal guidance on health regulation, medical licensing, patient rights, and ethics complaints.", publicAccess: false, professionalRequired: true, countries: ["NZ", "AU", "UK", "US", "CA", "IE", "SG", "IN"] },
  { slug: "elder-law", name: "Elder Law", category: "legal", description: "Specialist legal services for elderly clients including aged care, guardianship, and elder abuse.", publicAccess: false, professionalRequired: true, countries: ["NZ", "AU", "UK", "US", "CA", "IE", "SG", "IN"] },
  { slug: "animal-law", name: "Animal Law", category: "legal", description: "Legal advice on animal welfare, dangerous dog proceedings, and livestock disputes.", publicAccess: false, professionalRequired: true, countries: ["NZ", "AU", "UK", "US", "CA", "IE", "SG", "IN"] },
  { slug: "veterans-law", name: "Veterans' Law", category: "legal", description: "Legal support for veterans' benefits, pensions, disability claims, and service-related disputes.", publicAccess: false, professionalRequired: true, countries: ["NZ", "AU", "UK", "US", "CA", "IE", "IN"] },

  // =============================================
  // === TAX SERVICES (additional) ===
  // =============================================
  { slug: "capital-gains-tax", name: "Capital Gains Tax Advice & Filing", category: "tax", description: "Advice and filing for capital gains tax on property, shares, and other assets.", publicAccess: false, professionalRequired: true, countries: ["AU", "UK", "US", "CA", "IE", "SG", "IN"] },
  { slug: "fringe-benefit-tax", name: "Fringe Benefit Tax (FBT) Returns", category: "tax", description: "Calculate and file fringe benefit tax returns for employer-provided benefits.", publicAccess: false, professionalRequired: true, countries: ["NZ", "AU", "IN"], forms: ["IR420 (NZ)", "FBT Return (AU)"] },
  { slug: "withholding-tax-returns", name: "Withholding Tax Returns", category: "tax", description: "File withholding tax returns for payments to non-residents, contractors, and investments.", publicAccess: false, professionalRequired: true, countries: ["NZ", "AU", "UK", "US", "CA", "IE", "SG", "IN"] },
  { slug: "tax-residency-advice", name: "Tax Residency Advice", category: "tax", description: "Determine your tax residency status and obligations across multiple jurisdictions.", publicAccess: false, professionalRequired: true, countries: ["NZ", "AU", "UK", "US", "CA", "IE", "SG", "IN"] },
  { slug: "transfer-pricing", name: "Transfer Pricing", category: "tax", description: "Ensure related-party transactions comply with transfer pricing rules and documentation requirements.", publicAccess: false, professionalRequired: true, countries: ["NZ", "AU", "UK", "US", "CA", "IE", "SG", "IN"] },
  { slug: "rd-tax-incentive", name: "R&D Tax Incentive / Credit Claims", category: "tax", description: "Claim research and development tax incentives, credits, and offsets.", publicAccess: false, professionalRequired: true, countries: ["NZ", "AU", "UK", "US", "CA", "IE", "SG", "IN"] },
  { slug: "tax-audit-representation", name: "Tax Audit Representation", category: "tax", description: "Represent clients during tax audits and investigations by revenue authorities.", publicAccess: false, professionalRequired: true, countries: ["NZ", "AU", "UK", "US", "CA", "IE", "SG", "IN"] },
  { slug: "voluntary-disclosures", name: "Voluntary Disclosures", category: "tax", description: "Make voluntary disclosures to tax authorities for errors or omissions in past returns.", publicAccess: false, professionalRequired: true, countries: ["NZ", "AU", "UK", "US", "CA", "IE", "SG", "IN"] },
  { slug: "tax-debt-negotiation", name: "Tax Debt Negotiation", category: "tax", description: "Negotiate payment plans, write-offs, or compromises for outstanding tax debts.", publicAccess: false, professionalRequired: true, countries: ["NZ", "AU", "UK", "US", "CA", "IE", "SG", "IN"] },
  { slug: "estate-inheritance-tax-planning", name: "Estate & Inheritance Tax Planning", category: "tax", description: "Plan for estate duties, inheritance tax, and intergenerational wealth transfer.", publicAccess: false, professionalRequired: true, countries: ["UK", "US", "CA", "IE", "IN"] },
  { slug: "tax-exempt-organisation-returns", name: "Tax-Exempt Organisation Returns", category: "tax", description: "File annual returns and maintain tax-exempt status for charities and non-profits.", publicAccess: false, professionalRequired: true, countries: ["NZ", "AU", "UK", "US", "CA", "IE", "SG", "IN"], forms: ["Form 990 (US)", "Charities Return (NZ)", "ACNC Report (AU)"] },

  // =============================================
  // === BUSINESS ACCOUNTING SERVICES (additional) ===
  // =============================================
  { slug: "business-valuations", name: "Business Valuations", category: "accounting", description: "Determine the fair market value of a business for sale, investment, or dispute purposes.", publicAccess: false, professionalRequired: true, countries: ["NZ", "AU", "UK", "US", "CA", "IE", "SG", "IN"] },
  { slug: "cash-flow-forecasting", name: "Cash Flow Forecasting & Management", category: "accounting", description: "Build cash flow forecasts and implement management strategies to maintain liquidity.", publicAccess: false, professionalRequired: false, countries: ["NZ", "AU", "UK", "US", "CA", "IE", "SG", "IN"] },
  { slug: "budgeting-financial-planning", name: "Budgeting & Financial Planning", category: "accounting", description: "Create budgets and financial plans to guide business decision-making.", publicAccess: false, professionalRequired: false, countries: ["NZ", "AU", "UK", "US", "CA", "IE", "SG", "IN"] },
  { slug: "kpi-dashboard-monitoring", name: "KPI Dashboard Setup & Monitoring", category: "accounting", description: "Design and implement key performance indicator dashboards for real-time business insights.", publicAccess: false, professionalRequired: false, countries: ["NZ", "AU", "UK", "US", "CA", "IE", "SG", "IN"] },
  { slug: "benchmarking-industry-comparison", name: "Benchmarking & Industry Comparison", category: "accounting", description: "Compare your business performance against industry benchmarks and competitors.", publicAccess: false, professionalRequired: true, countries: ["NZ", "AU", "UK", "US", "CA", "IE", "SG", "IN"] },
  { slug: "business-succession-planning", name: "Business Succession Planning", category: "accounting", description: "Plan for ownership transition, retirement, and intergenerational business transfer.", publicAccess: false, professionalRequired: true, countries: ["NZ", "AU", "UK", "US", "CA", "IE", "SG", "IN"] },
  { slug: "franchise-accounting", name: "Franchise Accounting", category: "accounting", description: "Specialist accounting for franchise operations including royalty tracking and multi-site reporting.", publicAccess: false, professionalRequired: true, countries: ["NZ", "AU", "UK", "US", "CA", "IE", "SG", "IN"] },
  { slug: "agricultural-farm-accounting", name: "Agricultural / Farm Accounting", category: "accounting", description: "Specialist accounting for farms and agricultural businesses including livestock and crop valuations.", publicAccess: false, professionalRequired: true, countries: ["NZ", "AU", "UK", "US", "CA", "IE", "IN"] },
  { slug: "construction-industry-accounting", name: "Construction Industry Accounting", category: "accounting", description: "Accounting for construction companies including progress billing, retentions, and project costing.", publicAccess: false, professionalRequired: true, countries: ["NZ", "AU", "UK", "US", "CA", "IE", "SG", "IN"] },
  { slug: "medical-practice-accounting", name: "Medical Practice Accounting", category: "accounting", description: "Specialist accounting for doctors, dentists, and medical practices.", publicAccess: false, professionalRequired: true, countries: ["NZ", "AU", "UK", "US", "CA", "IE", "SG", "IN"] },
  { slug: "legal-practice-accounting", name: "Legal Practice Accounting", category: "accounting", description: "Accounting services tailored for law firms including trust account compliance.", publicAccess: false, professionalRequired: true, countries: ["NZ", "AU", "UK", "US", "CA", "IE", "SG", "IN"] },

  // =============================================
  // === COMPLIANCE (additional) ===
  // =============================================
  { slug: "annual-return-filing", name: "Annual Return Filing (Companies Office / ASIC / Companies House)", category: "accounting", description: "File annual returns and confirmations with the relevant companies registry.", publicAccess: true, professionalRequired: false, countries: ["NZ", "AU", "UK", "US", "CA", "IE", "SG", "IN"] },
  { slug: "directors-declarations", name: "Directors' Declarations", category: "accounting", description: "Prepare directors' declarations and solvency resolutions required by corporate law.", publicAccess: false, professionalRequired: true, countries: ["NZ", "AU", "UK", "US", "CA", "IE", "SG", "IN"] },
  { slug: "xbrl-ixbrl-filing", name: "XBRL Tagging & iXBRL Filing", category: "accounting", description: "Tag financial statements in XBRL/iXBRL format for regulatory filing.", publicAccess: false, professionalRequired: true, countries: ["UK", "US", "IE", "SG", "IN"] },
  { slug: "financial-statement-compilation", name: "Financial Statement Compilation", category: "accounting", description: "Compile financial statements from client-provided data without audit or review assurance.", publicAccess: false, professionalRequired: true, countries: ["NZ", "AU", "UK", "US", "CA", "IE", "SG", "IN"] },
  { slug: "financial-statement-review", name: "Financial Statement Review", category: "accounting", description: "Perform limited assurance reviews of financial statements.", publicAccess: false, professionalRequired: true, countries: ["NZ", "AU", "UK", "US", "CA", "IE", "SG", "IN"] },
  { slug: "full-audit-external", name: "Full Audit (External)", category: "accounting", description: "Conduct full external audits of financial statements for regulatory or stakeholder requirements.", publicAccess: false, professionalRequired: true, countries: ["NZ", "AU", "UK", "US", "CA", "IE", "SG", "IN"] },
  { slug: "internal-audit", name: "Internal Audit", category: "accounting", description: "Perform internal audits to assess risk management, controls, and governance processes.", publicAccess: false, professionalRequired: true, countries: ["NZ", "AU", "UK", "US", "CA", "IE", "SG", "IN"] },
  { slug: "sox-compliance", name: "SOX Compliance (US)", category: "accounting", description: "Ensure compliance with Sarbanes-Oxley Act requirements for internal controls and financial reporting.", publicAccess: false, professionalRequired: true, countries: ["US"] },
  { slug: "aml-cft-compliance-accounting", name: "AML/CFT Compliance (Accounting)", category: "accounting", description: "Meet anti-money laundering and countering financing of terrorism obligations for accounting practices.", publicAccess: false, professionalRequired: true, countries: ["NZ", "AU", "UK", "US", "CA", "IE", "SG", "IN"] },

  // =============================================
  // === ADVISORY (accounting) ===
  // =============================================
  { slug: "startup-financial-modelling", name: "Startup Financial Modelling", category: "accounting", description: "Build financial models for startups including revenue projections, burn rate, and runway analysis.", publicAccess: false, professionalRequired: true, countries: ["NZ", "AU", "UK", "US", "CA", "IE", "SG", "IN"] },
  { slug: "investor-ready-financial-packs", name: "Investor-Ready Financial Packs", category: "accounting", description: "Prepare investor-ready financial documentation including pitch deck financials and cap tables.", publicAccess: false, professionalRequired: true, countries: ["NZ", "AU", "UK", "US", "CA", "IE", "SG", "IN"] },
  { slug: "due-diligence-financial", name: "Due Diligence (Financial)", category: "accounting", description: "Conduct financial due diligence on acquisition targets, investments, or business partners.", publicAccess: false, professionalRequired: true, countries: ["NZ", "AU", "UK", "US", "CA", "IE", "SG", "IN"] },
  { slug: "expert-witness-accounting", name: "Expert Witness (Accounting)", category: "accounting", description: "Provide expert witness testimony and reports on accounting and financial matters in court.", publicAccess: false, professionalRequired: true, countries: ["NZ", "AU", "UK", "US", "CA", "IE", "SG", "IN"] },
  { slug: "litigation-support-accounting", name: "Litigation Support (Accounting)", category: "accounting", description: "Provide forensic accounting and financial analysis to support litigation proceedings.", publicAccess: false, professionalRequired: true, countries: ["NZ", "AU", "UK", "US", "CA", "IE", "SG", "IN"] },
  { slug: "insurance-claims-accounting", name: "Insurance Claims Accounting", category: "accounting", description: "Prepare and substantiate insurance claims with detailed financial evidence and loss quantification.", publicAccess: false, professionalRequired: true, countries: ["NZ", "AU", "UK", "US", "CA", "IE", "SG", "IN"] },
  { slug: "disaster-recovery-accounting", name: "Disaster Recovery Accounting", category: "accounting", description: "Reconstruct financial records and manage accounting recovery after disasters or data loss.", publicAccess: false, professionalRequired: true, countries: ["NZ", "AU", "UK", "US", "CA", "IE", "SG", "IN"] },

  // =============================================
  // === PAYROLL (additional) ===
  // =============================================
  { slug: "contractor-vs-employee-classification", name: "Contractor vs Employee Classification", category: "accounting", description: "Determine correct worker classification to ensure compliance with tax and employment laws.", publicAccess: true, professionalRequired: false, countries: ["NZ", "AU", "UK", "US", "CA", "IE", "SG", "IN"] },
  { slug: "employer-onboarding-registration", name: "Employer Onboarding & Registration", category: "accounting", description: "Register as an employer with tax authorities and set up payroll systems.", publicAccess: true, professionalRequired: false, countries: ["NZ", "AU", "UK", "US", "CA", "IE", "SG", "IN"] },
  { slug: "final-pay-termination-calculations", name: "Final Pay & Termination Calculations", category: "accounting", description: "Calculate final pay entitlements including unused leave, notice pay, and redundancy payments.", publicAccess: true, professionalRequired: false, countries: ["NZ", "AU", "UK", "US", "CA", "IE", "SG", "IN"] },
  { slug: "holiday-pay-calculations", name: "Holiday Pay Calculations", category: "accounting", description: "Calculate holiday pay entitlements including complex scenarios like irregular hours and shift work.", publicAccess: true, professionalRequired: false, countries: ["NZ", "AU", "UK", "US", "CA", "IE", "SG", "IN"] },
  { slug: "parental-leave-calculations", name: "Parental Leave Calculations", category: "accounting", description: "Calculate parental leave entitlements and government-funded parental leave payments.", publicAccess: true, professionalRequired: false, countries: ["NZ", "AU", "UK", "US", "CA", "IE", "SG", "IN"] },

  // =============================================
  // === PUBLIC SELF-SERVE TOOLS ===
  // =============================================
  { slug: "generate-will-online", name: "Generate a Will Online", category: "personal", description: "Create a basic last will and testament using our guided online tool.", publicAccess: true, professionalRequired: false, countries: ["NZ", "AU", "UK", "US", "CA", "IE", "SG", "IN"], forms: ["Simple Will"], estimatedCost: "From $49" },
  { slug: "generate-tenancy-agreement", name: "Generate a Tenancy Agreement", category: "property", description: "Create a residential tenancy or lease agreement customised for your jurisdiction.", publicAccess: true, professionalRequired: false, countries: ["NZ", "AU", "UK", "US", "CA", "IE", "SG", "IN"], forms: ["Residential Tenancy Agreement"], estimatedCost: "From $29" },
  { slug: "generate-employment-agreement", name: "Generate an Employment Agreement", category: "business", description: "Create a compliant employment agreement tailored to your country's labour laws.", publicAccess: true, professionalRequired: false, countries: ["NZ", "AU", "UK", "US", "CA", "IE", "SG", "IN"], forms: ["Individual Employment Agreement"], estimatedCost: "From $29" },
  { slug: "generate-privacy-policy", name: "Generate a Privacy Policy", category: "business", description: "Generate a privacy policy compliant with GDPR, NZ Privacy Act, AU APPs, and other frameworks.", publicAccess: true, professionalRequired: false, countries: ["NZ", "AU", "UK", "US", "CA", "IE", "SG", "IN"], estimatedCost: "Free" },
  { slug: "generate-terms-conditions", name: "Generate Terms & Conditions", category: "business", description: "Generate website or app terms and conditions customised for your business and jurisdiction.", publicAccess: true, professionalRequired: false, countries: ["NZ", "AU", "UK", "US", "CA", "IE", "SG", "IN"], estimatedCost: "Free" },
  { slug: "company-name-search", name: "Company Name Search", category: "business", description: "Search company registries to check if your desired company name is available.", publicAccess: true, professionalRequired: false, countries: ["NZ", "AU", "UK", "US", "CA", "IE", "SG", "IN"], estimatedCost: "Free" },
  { slug: "company-registration-self-serve", name: "Company Registration (Self-Serve)", category: "business", description: "Register a new company yourself using our guided step-by-step process.", publicAccess: true, professionalRequired: false, countries: ["NZ", "AU", "UK", "US", "CA", "IE", "SG", "IN"], estimatedCost: "From $99" },
  { slug: "abn-nzbn-ein-lookup", name: "ABN / NZBN / EIN Lookup", category: "business", description: "Look up business numbers including ABN (AU), NZBN (NZ), EIN (US), and company numbers.", publicAccess: true, professionalRequired: false, countries: ["NZ", "AU", "UK", "US", "CA", "IE", "SG", "IN"], estimatedCost: "Free" },
  { slug: "tax-calculator", name: "Tax Calculator (Estimate)", category: "tax", description: "Estimate your income tax, GST/VAT, or corporate tax obligations with our online calculator.", publicAccess: true, professionalRequired: false, countries: ["NZ", "AU", "UK", "US", "CA", "IE", "SG", "IN"], estimatedCost: "Free" },
  { slug: "child-support-calculator", name: "Child Support Calculator", category: "personal", description: "Estimate child support payments based on your jurisdiction's formula.", publicAccess: true, professionalRequired: false, countries: ["NZ", "AU", "UK", "US", "CA", "IE", "IN"], estimatedCost: "Free" },
  { slug: "mortgage-repayment-calculator", name: "Mortgage Repayment Calculator", category: "property", description: "Calculate mortgage repayments, interest costs, and compare loan scenarios.", publicAccess: true, professionalRequired: false, countries: ["NZ", "AU", "UK", "US", "CA", "IE", "SG", "IN"], estimatedCost: "Free" },
  { slug: "find-a-lawyer", name: "Find a Lawyer (Directory)", category: "legal", description: "Search our directory of verified lawyers by location, specialisation, and language.", publicAccess: true, professionalRequired: false, countries: ["NZ", "AU", "UK", "US", "CA", "IE", "SG", "IN"], estimatedCost: "Free" },
  { slug: "find-an-accountant", name: "Find an Accountant (Directory)", category: "accounting", description: "Search our directory of verified accountants by location, specialisation, and industry.", publicAccess: true, professionalRequired: false, countries: ["NZ", "AU", "UK", "US", "CA", "IE", "SG", "IN"], estimatedCost: "Free" },
  { slug: "legal-aid-eligibility-check", name: "Legal Aid Eligibility Check", category: "legal", description: "Check if you qualify for government-funded legal aid based on your income and case type.", publicAccess: true, professionalRequired: false, countries: ["NZ", "AU", "UK", "US", "CA", "IE", "IN"], estimatedCost: "Free" },
  { slug: "court-filing-fee-calculator", name: "Court Filing Fee Calculator", category: "court", description: "Calculate court filing fees for your jurisdiction and type of proceeding.", publicAccess: true, professionalRequired: false, countries: ["NZ", "AU", "UK", "US", "CA", "IE", "SG", "IN"], estimatedCost: "Free" },
];

export function getServicesByCountry(countryCode: string): Service[] {
  return SERVICES.filter(s => s.countries.includes(countryCode));
}

export function getServicesByCategory(category: Service["category"]): Service[] {
  return SERVICES.filter(s => s.category === category);
}

export function getPublicServices(countryCode: string): Service[] {
  return SERVICES.filter(s => s.countries.includes(countryCode) && s.publicAccess);
}

export function getProfessionalServices(countryCode: string): Service[] {
  return SERVICES.filter(s => s.countries.includes(countryCode) && s.professionalRequired);
}

export const SERVICE_CATEGORIES = [
  { slug: "personal", name: "Personal & Family", icon: "user", description: "Wills, estates, powers of attorney" },
  { slug: "property", name: "Property", icon: "home", description: "Buying, selling, renting property" },
  { slug: "business", name: "Business & Corporate", icon: "briefcase", description: "Company formation, contracts, trademarks" },
  { slug: "immigration", name: "Immigration", icon: "globe", description: "Visas, residency, citizenship" },
  { slug: "tax", name: "Tax", icon: "calculator", description: "Tax returns, GST/VAT, tax planning" },
  { slug: "accounting", name: "Accounting", icon: "chart", description: "Bookkeeping, payroll, financial statements" },
  { slug: "legal", name: "Legal & Disputes", icon: "scale", description: "Contracts, disputes, litigation" },
  { slug: "court", name: "Court & Filing", icon: "gavel", description: "Court filings, notarisation, apostille" },
] as const;
