import type { Metadata } from "next";
import Container from "@/app/components/shared/Container";
import Button from "@/app/components/shared/Button";
import Reveal from "@/app/components/effects/Reveal";

export const metadata: Metadata = {
  title: "Marco Reid for Startups — Legal and Accounting From Day One",
  description:
    "Company incorporation, legal compliance, accounting automation, and tax strategy — everything a startup needs from formation to funding, powered by AI.",
};

export default function ForStartupsPage() {
  return (
    <>
      <section className="bg-navy-500 pt-32 pb-20 sm:pt-40 sm:pb-28">
        <Container className="text-center">
          <h1 className="font-serif text-hero text-white">
            From formation to funding.
            <br />
            One platform.
          </h1>
          <p className="mx-auto mt-6 max-w-xl text-xl text-navy-200">
            Company incorporation. Legal compliance. Accounting automation.
            Tax strategy. Everything a startup needs from day one, powered by
            professionals who use the most advanced tools available.
          </p>
          <div className="mt-10 flex flex-wrap items-center justify-center gap-4">
            <Button href="/setup-company" size="lg">Set up a company</Button>
            <Button href="/post-matter" variant="secondary" size="lg">
              Post a matter
            </Button>
          </div>
        </Container>
      </section>

      <section className="py-24 sm:py-36" aria-label="Startup features">
        <Container>
          <Reveal>
            <h2 className="font-serif text-display text-navy-800">
              What Marco Reid does for startups.
            </h2>
          </Reveal>

          <div className="mt-16 space-y-4 max-w-3xl mx-auto">
            {[
              {
                title: "Intelligent company incorporation",
                desc: "Tell your lawyer where you want to operate and what the business does. Marco analyses entity types across jurisdictions, tax implications, and asset protection structures simultaneously. Formation documents generated, e-signed, and e-filed.",
              },
              {
                title: "Accounting from day one",
                desc: "Marco Reid Accounting connects to your bank feeds immediately. Every transaction categorised. Tax compliance automated from the first dollar. Your CPA sees everything in real time.",
              },
              {
                title: "Legal compliance built in",
                desc: "Employment contracts, NDAs, IP assignments, privacy policies — all generated by Document AI with legal vocabulary intelligence. E-signed inside the platform.",
              },
              {
                title: "Tax strategy across jurisdictions",
                desc: "Marco for Accounting analyses tax implications across every jurisdiction your startup operates in. R&D tax credits identified automatically. Transfer pricing documented from day one.",
              },
              {
                title: "Fundraising document management",
                desc: "Term sheets, SAFE notes, shareholder agreements — managed in the secure document vault. Data room access for investors through the client portal.",
              },
              {
                title: "IP protection",
                desc: "Marco for IP searches USPTO patent and trademark records, analyses prior art, and monitors for conflicting filings. Your startup’s intellectual property protected from day one.",
              },
            ].map((f) => (
              <Reveal key={f.title} delay={0.05}>
                <div className="rounded-xl border border-navy-100 bg-white p-6 shadow-card">
                  <h3 className="font-serif text-lg text-navy-700">{f.title}</h3>
                  <p className="mt-3 text-sm leading-relaxed text-navy-400">{f.desc}</p>
                </div>
              </Reveal>
            ))}
          </div>
        </Container>
      </section>

      <section className="py-24 sm:py-36" aria-label="From formation to funding">
        <Container>
          <Reveal>
            <h2 className="font-serif text-display text-navy-800">
              From formation to funding.
            </h2>
          </Reveal>

          <div className="mt-16 grid gap-6 sm:grid-cols-2 lg:grid-cols-4">
            {[
              { step: "1", title: "Company incorporation and entity structuring", desc: "The right entity type for your jurisdiction, tax situation, and growth plan." },
              { step: "2", title: "Founder agreements and IP assignment", desc: "Protect the company and every founder from day one." },
              { step: "3", title: "Accounting setup from day one", desc: "Books that investors trust. Clean financials from the first dollar." },
              { step: "4", title: "Fundraising document drafting", desc: "SAFEs, convertible notes, term sheets — drafted, reviewed, and ready." },
            ].map((s) => (
              <Reveal key={s.step} delay={0.05}>
                <div className="rounded-xl border border-navy-100 bg-white p-6 shadow-card">
                  <p className="text-xs font-bold text-gold-400">Step {s.step}</p>
                  <h3 className="mt-2 font-semibold text-navy-700">{s.title}</h3>
                  <p className="mt-3 text-sm leading-relaxed text-navy-400">{s.desc}</p>
                </div>
              </Reveal>
            ))}
          </div>
        </Container>
      </section>

      <section className="bg-navy-50 py-20 sm:py-28" aria-label="Testimonial">
        <div className="mx-auto max-w-3xl px-6 sm:px-8 lg:px-12 text-center">
          <Reveal>
            <p className="text-4xl text-gold-400">&ldquo;</p>
            <p className="mt-2 font-serif text-xl italic leading-relaxed text-navy-600">
              We incorporated, set up our books, and drafted our SAFE agreement — all through
              Marco Reid. Our seed round due diligence took 2 days instead of 2 weeks.
            </p>
            <p className="mt-6 text-sm font-semibold text-navy-700">Alex Kim</p>
            <p className="text-xs text-navy-400">Founder & CEO</p>
          </Reveal>
        </div>
      </section>

      <section className="py-24 sm:py-36" aria-label="Get in touch">
        <Container className="text-center">
          <Reveal>
            <h2 className="font-serif text-display text-navy-800">
              Ready to build?
            </h2>
            <p className="mt-4 text-lg text-navy-400">
              Talk to us about getting your startup set up on Marco Reid.
            </p>
          </Reveal>
          <Reveal delay={0.1}>
            <div className="mt-10 flex justify-center gap-4">
              <Button href="/contact" size="lg">Get in touch</Button>
            </div>
          </Reveal>
        </Container>
      </section>

      <section className="bg-navy-50 py-24 sm:py-36" aria-label="CTA">
        <Container className="text-center">
          <Reveal>
            <h2 className="font-serif text-display text-navy-800">
              Ready to build?
            </h2>
            <p className="mt-4 text-lg text-navy-400">
              From formation to funding. One platform. One team.
            </p>
          </Reveal>
          <Reveal delay={0.1}>
            <div className="mt-10 flex justify-center gap-4">
              <Button href="/pricing" size="lg">View pricing</Button>
              <Button href="/contact" variant="secondary" size="lg">Get in touch</Button>
            </div>
          </Reveal>
        </Container>
      </section>
    </>
  );
}
