import type { Metadata } from "next";
import Container from "@/app/components/shared/Container";
import Button from "@/app/components/shared/Button";
import Reveal from "@/app/components/effects/Reveal";

export const metadata: Metadata = {
  title: "AlecRae for Startups \u2014 Legal and Accounting From Day One",
  description:
    "Company incorporation, legal compliance, accounting automation, and tax strategy \u2014 everything a startup needs from formation to funding, powered by AI.",
};

export default function ForStartupsPage() {
  return (
    <>
      <section className="bg-navy-500 pt-32 pb-20 sm:pt-40 sm:pb-28">
        <Container className="text-center">
          <h1 className="font-serif text-hero text-white">
            From formation to funding.
            <br />
            One platform.
          </h1>
          <p className="mx-auto mt-6 max-w-xl text-xl text-navy-200">
            Company incorporation. Legal compliance. Accounting automation.
            Tax strategy. Everything a startup needs from day one, powered by
            professionals who use the most advanced tools available.
          </p>
        </Container>
      </section>

      <section className="py-24 sm:py-36" aria-label="Startup features">
        <Container>
          <Reveal>
            <h2 className="font-serif text-display text-navy-800">
              What AlecRae does for startups.
            </h2>
          </Reveal>

          <div className="mt-16 space-y-4 max-w-3xl mx-auto">
            {[
              {
                title: "Intelligent company incorporation",
                desc: "Tell your lawyer where you want to operate and what the business does. The Oracle analyses entity types across jurisdictions, tax implications, and asset protection structures simultaneously. Formation documents generated, e-signed, and e-filed.",
              },
              {
                title: "Accounting from day one",
                desc: "AlecRae Accounting connects to your bank feeds immediately. Every transaction categorised. Tax compliance automated from the first dollar. Your CPA sees everything in real time.",
              },
              {
                title: "Legal compliance built in",
                desc: "Employment contracts, NDAs, IP assignments, privacy policies \u2014 all generated by Document AI with legal vocabulary intelligence. E-signed inside the platform.",
              },
              {
                title: "Tax strategy across jurisdictions",
                desc: "The Oracle for Accounting analyses tax implications across every jurisdiction your startup operates in. R&D tax credits identified automatically. Transfer pricing documented from day one.",
              },
              {
                title: "Fundraising document management",
                desc: "Term sheets, SAFE notes, shareholder agreements \u2014 managed in the secure document vault. Data room access for investors through the client portal.",
              },
              {
                title: "IP protection",
                desc: "The Oracle for IP searches USPTO patent and trademark records, analyses prior art, and monitors for conflicting filings. Your startup\u2019s intellectual property protected from day one.",
              },
            ].map((f) => (
              <Reveal key={f.title} delay={0.05}>
                <div className="rounded-xl border border-navy-100 bg-white p-6 shadow-card">
                  <h3 className="font-serif text-lg text-navy-700">{f.title}</h3>
                  <p className="mt-3 text-sm leading-relaxed text-navy-400">{f.desc}</p>
                </div>
              </Reveal>
            ))}
          </div>
        </Container>
      </section>

      <section className="bg-navy-50 py-24 sm:py-36" aria-label="CTA">
        <Container className="text-center">
          <Reveal>
            <h2 className="font-serif text-display text-navy-800">
              Ready to build?
            </h2>
            <p className="mt-4 text-lg text-navy-400">
              From formation to funding. One platform. One team.
            </p>
          </Reveal>
          <Reveal delay={0.1}>
            <div className="mt-10 flex justify-center gap-4">
              <Button href="/pricing" size="lg">View pricing</Button>
              <Button href="/contact" variant="secondary" size="lg">Get in touch</Button>
            </div>
          </Reveal>
        </Container>
      </section>
    </>
  );
}
